// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: AdvInfoFieldRef.proto

package ru.sovcombank.hackaton.proto;

public final class AdvInfoFieldRefProto {
  private AdvInfoFieldRefProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ru_sovcombank_hackaton_proto_AdvInfoFieldRef_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ru_sovcombank_hackaton_proto_AdvInfoFieldRef_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\025AdvInfoFieldRef.proto\022\034ru.sovcombank.h" +
      "ackaton.proto\032\022MessageEnums.proto\"|\n\017Adv" +
      "InfoFieldRef\022\r\n\005alias\030\001 \001(\t\022\024\n\007caption\030\002" +
      " \001(\tH\000\210\001\001\0228\n\010dataType\030\003 \001(\0162&.ru.sovcomb" +
      "ank.hackaton.proto.DataTypeB\n\n\010_captionB" +
      "\032B\024AdvInfoFieldRefProtoH\001P\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          ru.sovcombank.hackaton.proto.MessageEnumsProto.getDescriptor(),
        });
    internal_static_ru_sovcombank_hackaton_proto_AdvInfoFieldRef_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_ru_sovcombank_hackaton_proto_AdvInfoFieldRef_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ru_sovcombank_hackaton_proto_AdvInfoFieldRef_descriptor,
        new java.lang.String[] { "Alias", "Caption", "DataType", "Caption", });
    ru.sovcombank.hackaton.proto.MessageEnumsProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
