// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: AdvInfoData.proto

package ru.sovcombank.hackaton.proto;

/**
 * <pre>
 **
 *Тип данных для типа расширенного отображения статуса.
 *Поле fullOrIncrement - обязательно для заполнения.
 *Если поле fullOrIncrement = false, а поле rows не содержит данных, то со стороны GUI данные в статусе необходимо стирать полностью.
 *Поле fullOrIncrement регламентирует правила изменения данных в строках расширенного статуса.
 *При значении false данные в GUI полностью заменяются данными из коллекции rows, в обратном случае действует следующее правило:
 *1. Если строки с данными из поля rows нет в GUI значит ее нужно добавить
 *2. Если строка с данными из поля rows есть в GUI значит значения полей в GUI нужно заменить значениями полей из пришедшей строки
 *3. Если строка с данными из поля rows помечена флагом incrementDelete = true значит эта строка должна быть удалена из GUI
 * </pre>
 *
 * Protobuf type {@code ru.sovcombank.hackaton.proto.AdvInfoData}
 */
public final class AdvInfoData extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:ru.sovcombank.hackaton.proto.AdvInfoData)
    AdvInfoDataOrBuilder {
private static final long serialVersionUID = 0L;
  // Use AdvInfoData.newBuilder() to construct.
  private AdvInfoData(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private AdvInfoData() {
    rows_ = java.util.Collections.emptyList();
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new AdvInfoData();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return ru.sovcombank.hackaton.proto.AdvInfoDataProto.internal_static_ru_sovcombank_hackaton_proto_AdvInfoData_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return ru.sovcombank.hackaton.proto.AdvInfoDataProto.internal_static_ru_sovcombank_hackaton_proto_AdvInfoData_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            ru.sovcombank.hackaton.proto.AdvInfoData.class, ru.sovcombank.hackaton.proto.AdvInfoData.Builder.class);
  }

  public static final int FULLORINCREMENT_FIELD_NUMBER = 1;
  private boolean fullOrIncrement_ = false;
  /**
   * <pre>
   * Флаг указывающий на полное обновление данных или инкрементальное
   * </pre>
   *
   * <code>bool fullOrIncrement = 1;</code>
   * @return The fullOrIncrement.
   */
  @java.lang.Override
  public boolean getFullOrIncrement() {
    return fullOrIncrement_;
  }

  public static final int ROWS_FIELD_NUMBER = 2;
  @SuppressWarnings("serial")
  private java.util.List<ru.sovcombank.hackaton.proto.DataRow> rows_;
  /**
   * <pre>
   * Записи со значениями полей
   * </pre>
   *
   * <code>repeated .ru.sovcombank.hackaton.proto.DataRow rows = 2;</code>
   */
  @java.lang.Override
  public java.util.List<ru.sovcombank.hackaton.proto.DataRow> getRowsList() {
    return rows_;
  }
  /**
   * <pre>
   * Записи со значениями полей
   * </pre>
   *
   * <code>repeated .ru.sovcombank.hackaton.proto.DataRow rows = 2;</code>
   */
  @java.lang.Override
  public java.util.List<? extends ru.sovcombank.hackaton.proto.DataRowOrBuilder> 
      getRowsOrBuilderList() {
    return rows_;
  }
  /**
   * <pre>
   * Записи со значениями полей
   * </pre>
   *
   * <code>repeated .ru.sovcombank.hackaton.proto.DataRow rows = 2;</code>
   */
  @java.lang.Override
  public int getRowsCount() {
    return rows_.size();
  }
  /**
   * <pre>
   * Записи со значениями полей
   * </pre>
   *
   * <code>repeated .ru.sovcombank.hackaton.proto.DataRow rows = 2;</code>
   */
  @java.lang.Override
  public ru.sovcombank.hackaton.proto.DataRow getRows(int index) {
    return rows_.get(index);
  }
  /**
   * <pre>
   * Записи со значениями полей
   * </pre>
   *
   * <code>repeated .ru.sovcombank.hackaton.proto.DataRow rows = 2;</code>
   */
  @java.lang.Override
  public ru.sovcombank.hackaton.proto.DataRowOrBuilder getRowsOrBuilder(
      int index) {
    return rows_.get(index);
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (fullOrIncrement_ != false) {
      output.writeBool(1, fullOrIncrement_);
    }
    for (int i = 0; i < rows_.size(); i++) {
      output.writeMessage(2, rows_.get(i));
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (fullOrIncrement_ != false) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(1, fullOrIncrement_);
    }
    for (int i = 0; i < rows_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(2, rows_.get(i));
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof ru.sovcombank.hackaton.proto.AdvInfoData)) {
      return super.equals(obj);
    }
    ru.sovcombank.hackaton.proto.AdvInfoData other = (ru.sovcombank.hackaton.proto.AdvInfoData) obj;

    if (getFullOrIncrement()
        != other.getFullOrIncrement()) return false;
    if (!getRowsList()
        .equals(other.getRowsList())) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + FULLORINCREMENT_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
        getFullOrIncrement());
    if (getRowsCount() > 0) {
      hash = (37 * hash) + ROWS_FIELD_NUMBER;
      hash = (53 * hash) + getRowsList().hashCode();
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static ru.sovcombank.hackaton.proto.AdvInfoData parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static ru.sovcombank.hackaton.proto.AdvInfoData parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static ru.sovcombank.hackaton.proto.AdvInfoData parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static ru.sovcombank.hackaton.proto.AdvInfoData parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static ru.sovcombank.hackaton.proto.AdvInfoData parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static ru.sovcombank.hackaton.proto.AdvInfoData parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static ru.sovcombank.hackaton.proto.AdvInfoData parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static ru.sovcombank.hackaton.proto.AdvInfoData parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static ru.sovcombank.hackaton.proto.AdvInfoData parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static ru.sovcombank.hackaton.proto.AdvInfoData parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static ru.sovcombank.hackaton.proto.AdvInfoData parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static ru.sovcombank.hackaton.proto.AdvInfoData parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(ru.sovcombank.hackaton.proto.AdvInfoData prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   **
   *Тип данных для типа расширенного отображения статуса.
   *Поле fullOrIncrement - обязательно для заполнения.
   *Если поле fullOrIncrement = false, а поле rows не содержит данных, то со стороны GUI данные в статусе необходимо стирать полностью.
   *Поле fullOrIncrement регламентирует правила изменения данных в строках расширенного статуса.
   *При значении false данные в GUI полностью заменяются данными из коллекции rows, в обратном случае действует следующее правило:
   *1. Если строки с данными из поля rows нет в GUI значит ее нужно добавить
   *2. Если строка с данными из поля rows есть в GUI значит значения полей в GUI нужно заменить значениями полей из пришедшей строки
   *3. Если строка с данными из поля rows помечена флагом incrementDelete = true значит эта строка должна быть удалена из GUI
   * </pre>
   *
   * Protobuf type {@code ru.sovcombank.hackaton.proto.AdvInfoData}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:ru.sovcombank.hackaton.proto.AdvInfoData)
      ru.sovcombank.hackaton.proto.AdvInfoDataOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return ru.sovcombank.hackaton.proto.AdvInfoDataProto.internal_static_ru_sovcombank_hackaton_proto_AdvInfoData_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return ru.sovcombank.hackaton.proto.AdvInfoDataProto.internal_static_ru_sovcombank_hackaton_proto_AdvInfoData_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              ru.sovcombank.hackaton.proto.AdvInfoData.class, ru.sovcombank.hackaton.proto.AdvInfoData.Builder.class);
    }

    // Construct using ru.sovcombank.hackaton.proto.AdvInfoData.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      fullOrIncrement_ = false;
      if (rowsBuilder_ == null) {
        rows_ = java.util.Collections.emptyList();
      } else {
        rows_ = null;
        rowsBuilder_.clear();
      }
      bitField0_ = (bitField0_ & ~0x00000002);
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return ru.sovcombank.hackaton.proto.AdvInfoDataProto.internal_static_ru_sovcombank_hackaton_proto_AdvInfoData_descriptor;
    }

    @java.lang.Override
    public ru.sovcombank.hackaton.proto.AdvInfoData getDefaultInstanceForType() {
      return ru.sovcombank.hackaton.proto.AdvInfoData.getDefaultInstance();
    }

    @java.lang.Override
    public ru.sovcombank.hackaton.proto.AdvInfoData build() {
      ru.sovcombank.hackaton.proto.AdvInfoData result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public ru.sovcombank.hackaton.proto.AdvInfoData buildPartial() {
      ru.sovcombank.hackaton.proto.AdvInfoData result = new ru.sovcombank.hackaton.proto.AdvInfoData(this);
      buildPartialRepeatedFields(result);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartialRepeatedFields(ru.sovcombank.hackaton.proto.AdvInfoData result) {
      if (rowsBuilder_ == null) {
        if (((bitField0_ & 0x00000002) != 0)) {
          rows_ = java.util.Collections.unmodifiableList(rows_);
          bitField0_ = (bitField0_ & ~0x00000002);
        }
        result.rows_ = rows_;
      } else {
        result.rows_ = rowsBuilder_.build();
      }
    }

    private void buildPartial0(ru.sovcombank.hackaton.proto.AdvInfoData result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.fullOrIncrement_ = fullOrIncrement_;
      }
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof ru.sovcombank.hackaton.proto.AdvInfoData) {
        return mergeFrom((ru.sovcombank.hackaton.proto.AdvInfoData)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(ru.sovcombank.hackaton.proto.AdvInfoData other) {
      if (other == ru.sovcombank.hackaton.proto.AdvInfoData.getDefaultInstance()) return this;
      if (other.getFullOrIncrement() != false) {
        setFullOrIncrement(other.getFullOrIncrement());
      }
      if (rowsBuilder_ == null) {
        if (!other.rows_.isEmpty()) {
          if (rows_.isEmpty()) {
            rows_ = other.rows_;
            bitField0_ = (bitField0_ & ~0x00000002);
          } else {
            ensureRowsIsMutable();
            rows_.addAll(other.rows_);
          }
          onChanged();
        }
      } else {
        if (!other.rows_.isEmpty()) {
          if (rowsBuilder_.isEmpty()) {
            rowsBuilder_.dispose();
            rowsBuilder_ = null;
            rows_ = other.rows_;
            bitField0_ = (bitField0_ & ~0x00000002);
            rowsBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getRowsFieldBuilder() : null;
          } else {
            rowsBuilder_.addAllMessages(other.rows_);
          }
        }
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              fullOrIncrement_ = input.readBool();
              bitField0_ |= 0x00000001;
              break;
            } // case 8
            case 18: {
              ru.sovcombank.hackaton.proto.DataRow m =
                  input.readMessage(
                      ru.sovcombank.hackaton.proto.DataRow.parser(),
                      extensionRegistry);
              if (rowsBuilder_ == null) {
                ensureRowsIsMutable();
                rows_.add(m);
              } else {
                rowsBuilder_.addMessage(m);
              }
              break;
            } // case 18
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private boolean fullOrIncrement_ ;
    /**
     * <pre>
     * Флаг указывающий на полное обновление данных или инкрементальное
     * </pre>
     *
     * <code>bool fullOrIncrement = 1;</code>
     * @return The fullOrIncrement.
     */
    @java.lang.Override
    public boolean getFullOrIncrement() {
      return fullOrIncrement_;
    }
    /**
     * <pre>
     * Флаг указывающий на полное обновление данных или инкрементальное
     * </pre>
     *
     * <code>bool fullOrIncrement = 1;</code>
     * @param value The fullOrIncrement to set.
     * @return This builder for chaining.
     */
    public Builder setFullOrIncrement(boolean value) {
      
      fullOrIncrement_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Флаг указывающий на полное обновление данных или инкрементальное
     * </pre>
     *
     * <code>bool fullOrIncrement = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearFullOrIncrement() {
      bitField0_ = (bitField0_ & ~0x00000001);
      fullOrIncrement_ = false;
      onChanged();
      return this;
    }

    private java.util.List<ru.sovcombank.hackaton.proto.DataRow> rows_ =
      java.util.Collections.emptyList();
    private void ensureRowsIsMutable() {
      if (!((bitField0_ & 0x00000002) != 0)) {
        rows_ = new java.util.ArrayList<ru.sovcombank.hackaton.proto.DataRow>(rows_);
        bitField0_ |= 0x00000002;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        ru.sovcombank.hackaton.proto.DataRow, ru.sovcombank.hackaton.proto.DataRow.Builder, ru.sovcombank.hackaton.proto.DataRowOrBuilder> rowsBuilder_;

    /**
     * <pre>
     * Записи со значениями полей
     * </pre>
     *
     * <code>repeated .ru.sovcombank.hackaton.proto.DataRow rows = 2;</code>
     */
    public java.util.List<ru.sovcombank.hackaton.proto.DataRow> getRowsList() {
      if (rowsBuilder_ == null) {
        return java.util.Collections.unmodifiableList(rows_);
      } else {
        return rowsBuilder_.getMessageList();
      }
    }
    /**
     * <pre>
     * Записи со значениями полей
     * </pre>
     *
     * <code>repeated .ru.sovcombank.hackaton.proto.DataRow rows = 2;</code>
     */
    public int getRowsCount() {
      if (rowsBuilder_ == null) {
        return rows_.size();
      } else {
        return rowsBuilder_.getCount();
      }
    }
    /**
     * <pre>
     * Записи со значениями полей
     * </pre>
     *
     * <code>repeated .ru.sovcombank.hackaton.proto.DataRow rows = 2;</code>
     */
    public ru.sovcombank.hackaton.proto.DataRow getRows(int index) {
      if (rowsBuilder_ == null) {
        return rows_.get(index);
      } else {
        return rowsBuilder_.getMessage(index);
      }
    }
    /**
     * <pre>
     * Записи со значениями полей
     * </pre>
     *
     * <code>repeated .ru.sovcombank.hackaton.proto.DataRow rows = 2;</code>
     */
    public Builder setRows(
        int index, ru.sovcombank.hackaton.proto.DataRow value) {
      if (rowsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureRowsIsMutable();
        rows_.set(index, value);
        onChanged();
      } else {
        rowsBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <pre>
     * Записи со значениями полей
     * </pre>
     *
     * <code>repeated .ru.sovcombank.hackaton.proto.DataRow rows = 2;</code>
     */
    public Builder setRows(
        int index, ru.sovcombank.hackaton.proto.DataRow.Builder builderForValue) {
      if (rowsBuilder_ == null) {
        ensureRowsIsMutable();
        rows_.set(index, builderForValue.build());
        onChanged();
      } else {
        rowsBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <pre>
     * Записи со значениями полей
     * </pre>
     *
     * <code>repeated .ru.sovcombank.hackaton.proto.DataRow rows = 2;</code>
     */
    public Builder addRows(ru.sovcombank.hackaton.proto.DataRow value) {
      if (rowsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureRowsIsMutable();
        rows_.add(value);
        onChanged();
      } else {
        rowsBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <pre>
     * Записи со значениями полей
     * </pre>
     *
     * <code>repeated .ru.sovcombank.hackaton.proto.DataRow rows = 2;</code>
     */
    public Builder addRows(
        int index, ru.sovcombank.hackaton.proto.DataRow value) {
      if (rowsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureRowsIsMutable();
        rows_.add(index, value);
        onChanged();
      } else {
        rowsBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <pre>
     * Записи со значениями полей
     * </pre>
     *
     * <code>repeated .ru.sovcombank.hackaton.proto.DataRow rows = 2;</code>
     */
    public Builder addRows(
        ru.sovcombank.hackaton.proto.DataRow.Builder builderForValue) {
      if (rowsBuilder_ == null) {
        ensureRowsIsMutable();
        rows_.add(builderForValue.build());
        onChanged();
      } else {
        rowsBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <pre>
     * Записи со значениями полей
     * </pre>
     *
     * <code>repeated .ru.sovcombank.hackaton.proto.DataRow rows = 2;</code>
     */
    public Builder addRows(
        int index, ru.sovcombank.hackaton.proto.DataRow.Builder builderForValue) {
      if (rowsBuilder_ == null) {
        ensureRowsIsMutable();
        rows_.add(index, builderForValue.build());
        onChanged();
      } else {
        rowsBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <pre>
     * Записи со значениями полей
     * </pre>
     *
     * <code>repeated .ru.sovcombank.hackaton.proto.DataRow rows = 2;</code>
     */
    public Builder addAllRows(
        java.lang.Iterable<? extends ru.sovcombank.hackaton.proto.DataRow> values) {
      if (rowsBuilder_ == null) {
        ensureRowsIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, rows_);
        onChanged();
      } else {
        rowsBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <pre>
     * Записи со значениями полей
     * </pre>
     *
     * <code>repeated .ru.sovcombank.hackaton.proto.DataRow rows = 2;</code>
     */
    public Builder clearRows() {
      if (rowsBuilder_ == null) {
        rows_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000002);
        onChanged();
      } else {
        rowsBuilder_.clear();
      }
      return this;
    }
    /**
     * <pre>
     * Записи со значениями полей
     * </pre>
     *
     * <code>repeated .ru.sovcombank.hackaton.proto.DataRow rows = 2;</code>
     */
    public Builder removeRows(int index) {
      if (rowsBuilder_ == null) {
        ensureRowsIsMutable();
        rows_.remove(index);
        onChanged();
      } else {
        rowsBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <pre>
     * Записи со значениями полей
     * </pre>
     *
     * <code>repeated .ru.sovcombank.hackaton.proto.DataRow rows = 2;</code>
     */
    public ru.sovcombank.hackaton.proto.DataRow.Builder getRowsBuilder(
        int index) {
      return getRowsFieldBuilder().getBuilder(index);
    }
    /**
     * <pre>
     * Записи со значениями полей
     * </pre>
     *
     * <code>repeated .ru.sovcombank.hackaton.proto.DataRow rows = 2;</code>
     */
    public ru.sovcombank.hackaton.proto.DataRowOrBuilder getRowsOrBuilder(
        int index) {
      if (rowsBuilder_ == null) {
        return rows_.get(index);  } else {
        return rowsBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <pre>
     * Записи со значениями полей
     * </pre>
     *
     * <code>repeated .ru.sovcombank.hackaton.proto.DataRow rows = 2;</code>
     */
    public java.util.List<? extends ru.sovcombank.hackaton.proto.DataRowOrBuilder> 
         getRowsOrBuilderList() {
      if (rowsBuilder_ != null) {
        return rowsBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(rows_);
      }
    }
    /**
     * <pre>
     * Записи со значениями полей
     * </pre>
     *
     * <code>repeated .ru.sovcombank.hackaton.proto.DataRow rows = 2;</code>
     */
    public ru.sovcombank.hackaton.proto.DataRow.Builder addRowsBuilder() {
      return getRowsFieldBuilder().addBuilder(
          ru.sovcombank.hackaton.proto.DataRow.getDefaultInstance());
    }
    /**
     * <pre>
     * Записи со значениями полей
     * </pre>
     *
     * <code>repeated .ru.sovcombank.hackaton.proto.DataRow rows = 2;</code>
     */
    public ru.sovcombank.hackaton.proto.DataRow.Builder addRowsBuilder(
        int index) {
      return getRowsFieldBuilder().addBuilder(
          index, ru.sovcombank.hackaton.proto.DataRow.getDefaultInstance());
    }
    /**
     * <pre>
     * Записи со значениями полей
     * </pre>
     *
     * <code>repeated .ru.sovcombank.hackaton.proto.DataRow rows = 2;</code>
     */
    public java.util.List<ru.sovcombank.hackaton.proto.DataRow.Builder> 
         getRowsBuilderList() {
      return getRowsFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        ru.sovcombank.hackaton.proto.DataRow, ru.sovcombank.hackaton.proto.DataRow.Builder, ru.sovcombank.hackaton.proto.DataRowOrBuilder> 
        getRowsFieldBuilder() {
      if (rowsBuilder_ == null) {
        rowsBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            ru.sovcombank.hackaton.proto.DataRow, ru.sovcombank.hackaton.proto.DataRow.Builder, ru.sovcombank.hackaton.proto.DataRowOrBuilder>(
                rows_,
                ((bitField0_ & 0x00000002) != 0),
                getParentForChildren(),
                isClean());
        rows_ = null;
      }
      return rowsBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:ru.sovcombank.hackaton.proto.AdvInfoData)
  }

  // @@protoc_insertion_point(class_scope:ru.sovcombank.hackaton.proto.AdvInfoData)
  private static final ru.sovcombank.hackaton.proto.AdvInfoData DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new ru.sovcombank.hackaton.proto.AdvInfoData();
  }

  public static ru.sovcombank.hackaton.proto.AdvInfoData getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<AdvInfoData>
      PARSER = new com.google.protobuf.AbstractParser<AdvInfoData>() {
    @java.lang.Override
    public AdvInfoData parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<AdvInfoData> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<AdvInfoData> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public ru.sovcombank.hackaton.proto.AdvInfoData getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

