// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: AdvInfoData.proto

package ru.sovcombank.hackaton.proto;

public interface AdvInfoDataOrBuilder extends
    // @@protoc_insertion_point(interface_extends:ru.sovcombank.hackaton.proto.AdvInfoData)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * Флаг указывающий на полное обновление данных или инкрементальное
   * </pre>
   *
   * <code>bool fullOrIncrement = 1;</code>
   * @return The fullOrIncrement.
   */
  boolean getFullOrIncrement();

  /**
   * <pre>
   * Записи со значениями полей
   * </pre>
   *
   * <code>repeated .ru.sovcombank.hackaton.proto.DataRow rows = 2;</code>
   */
  java.util.List<ru.sovcombank.hackaton.proto.DataRow> 
      getRowsList();
  /**
   * <pre>
   * Записи со значениями полей
   * </pre>
   *
   * <code>repeated .ru.sovcombank.hackaton.proto.DataRow rows = 2;</code>
   */
  ru.sovcombank.hackaton.proto.DataRow getRows(int index);
  /**
   * <pre>
   * Записи со значениями полей
   * </pre>
   *
   * <code>repeated .ru.sovcombank.hackaton.proto.DataRow rows = 2;</code>
   */
  int getRowsCount();
  /**
   * <pre>
   * Записи со значениями полей
   * </pre>
   *
   * <code>repeated .ru.sovcombank.hackaton.proto.DataRow rows = 2;</code>
   */
  java.util.List<? extends ru.sovcombank.hackaton.proto.DataRowOrBuilder> 
      getRowsOrBuilderList();
  /**
   * <pre>
   * Записи со значениями полей
   * </pre>
   *
   * <code>repeated .ru.sovcombank.hackaton.proto.DataRow rows = 2;</code>
   */
  ru.sovcombank.hackaton.proto.DataRowOrBuilder getRowsOrBuilder(
      int index);
}
