// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: AdvInfoData.proto

package ru.sovcombank.hackaton.proto;

public final class AdvInfoDataProto {
  private AdvInfoDataProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ru_sovcombank_hackaton_proto_AdvInfoData_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ru_sovcombank_hackaton_proto_AdvInfoData_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\021AdvInfoData.proto\022\034ru.sovcombank.hacka" +
      "ton.proto\032\rDataRow.proto\"[\n\013AdvInfoData\022" +
      "\027\n\017fullOrIncrement\030\001 \001(\010\0223\n\004rows\030\002 \003(\0132%" +
      ".ru.sovcombank.hackaton.proto.DataRowB\026B" +
      "\020AdvInfoDataProtoH\001P\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          ru.sovcombank.hackaton.proto.DataRowProto.getDescriptor(),
        });
    internal_static_ru_sovcombank_hackaton_proto_AdvInfoData_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_ru_sovcombank_hackaton_proto_AdvInfoData_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ru_sovcombank_hackaton_proto_AdvInfoData_descriptor,
        new java.lang.String[] { "FullOrIncrement", "Rows", });
    ru.sovcombank.hackaton.proto.DataRowProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
