// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: DataRow.proto

package ru.sovcombank.hackaton.proto;

/**
 * Protobuf type {@code ru.sovcombank.hackaton.proto.DataRow}
 */
public final class DataRow extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:ru.sovcombank.hackaton.proto.DataRow)
    DataRowOrBuilder {
private static final long serialVersionUID = 0L;
  // Use DataRow.newBuilder() to construct.
  private DataRow(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private DataRow() {
    rowIdent_ = "";
    values_ = java.util.Collections.emptyList();
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new DataRow();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return ru.sovcombank.hackaton.proto.DataRowProto.internal_static_ru_sovcombank_hackaton_proto_DataRow_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return ru.sovcombank.hackaton.proto.DataRowProto.internal_static_ru_sovcombank_hackaton_proto_DataRow_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            ru.sovcombank.hackaton.proto.DataRow.class, ru.sovcombank.hackaton.proto.DataRow.Builder.class);
  }

  public static final int ROWIDENT_FIELD_NUMBER = 1;
  @SuppressWarnings("serial")
  private volatile java.lang.Object rowIdent_ = "";
  /**
   * <pre>
   * Идентификатор записи
   * </pre>
   *
   * <code>string rowIdent = 1;</code>
   * @return The rowIdent.
   */
  @java.lang.Override
  public java.lang.String getRowIdent() {
    java.lang.Object ref = rowIdent_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      rowIdent_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * Идентификатор записи
   * </pre>
   *
   * <code>string rowIdent = 1;</code>
   * @return The bytes for rowIdent.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getRowIdentBytes() {
    java.lang.Object ref = rowIdent_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      rowIdent_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int INCREMENTDELETE_FIELD_NUMBER = 2;
  private boolean incrementDelete_ = false;
  /**
   * <pre>
   * Инкрементальное удаление записи (Удаление записи при инкрементальной передаче данных)
   * </pre>
   *
   * <code>bool incrementDelete = 2;</code>
   * @return The incrementDelete.
   */
  @java.lang.Override
  public boolean getIncrementDelete() {
    return incrementDelete_;
  }

  public static final int VALUES_FIELD_NUMBER = 3;
  @SuppressWarnings("serial")
  private java.util.List<ru.sovcombank.hackaton.proto.ValueRef> values_;
  /**
   * <pre>
   * Описание значения поля
   * </pre>
   *
   * <code>repeated .ru.sovcombank.hackaton.proto.ValueRef values = 3;</code>
   */
  @java.lang.Override
  public java.util.List<ru.sovcombank.hackaton.proto.ValueRef> getValuesList() {
    return values_;
  }
  /**
   * <pre>
   * Описание значения поля
   * </pre>
   *
   * <code>repeated .ru.sovcombank.hackaton.proto.ValueRef values = 3;</code>
   */
  @java.lang.Override
  public java.util.List<? extends ru.sovcombank.hackaton.proto.ValueRefOrBuilder> 
      getValuesOrBuilderList() {
    return values_;
  }
  /**
   * <pre>
   * Описание значения поля
   * </pre>
   *
   * <code>repeated .ru.sovcombank.hackaton.proto.ValueRef values = 3;</code>
   */
  @java.lang.Override
  public int getValuesCount() {
    return values_.size();
  }
  /**
   * <pre>
   * Описание значения поля
   * </pre>
   *
   * <code>repeated .ru.sovcombank.hackaton.proto.ValueRef values = 3;</code>
   */
  @java.lang.Override
  public ru.sovcombank.hackaton.proto.ValueRef getValues(int index) {
    return values_.get(index);
  }
  /**
   * <pre>
   * Описание значения поля
   * </pre>
   *
   * <code>repeated .ru.sovcombank.hackaton.proto.ValueRef values = 3;</code>
   */
  @java.lang.Override
  public ru.sovcombank.hackaton.proto.ValueRefOrBuilder getValuesOrBuilder(
      int index) {
    return values_.get(index);
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(rowIdent_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, rowIdent_);
    }
    if (incrementDelete_ != false) {
      output.writeBool(2, incrementDelete_);
    }
    for (int i = 0; i < values_.size(); i++) {
      output.writeMessage(3, values_.get(i));
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(rowIdent_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, rowIdent_);
    }
    if (incrementDelete_ != false) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(2, incrementDelete_);
    }
    for (int i = 0; i < values_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(3, values_.get(i));
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof ru.sovcombank.hackaton.proto.DataRow)) {
      return super.equals(obj);
    }
    ru.sovcombank.hackaton.proto.DataRow other = (ru.sovcombank.hackaton.proto.DataRow) obj;

    if (!getRowIdent()
        .equals(other.getRowIdent())) return false;
    if (getIncrementDelete()
        != other.getIncrementDelete()) return false;
    if (!getValuesList()
        .equals(other.getValuesList())) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + ROWIDENT_FIELD_NUMBER;
    hash = (53 * hash) + getRowIdent().hashCode();
    hash = (37 * hash) + INCREMENTDELETE_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
        getIncrementDelete());
    if (getValuesCount() > 0) {
      hash = (37 * hash) + VALUES_FIELD_NUMBER;
      hash = (53 * hash) + getValuesList().hashCode();
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static ru.sovcombank.hackaton.proto.DataRow parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static ru.sovcombank.hackaton.proto.DataRow parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static ru.sovcombank.hackaton.proto.DataRow parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static ru.sovcombank.hackaton.proto.DataRow parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static ru.sovcombank.hackaton.proto.DataRow parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static ru.sovcombank.hackaton.proto.DataRow parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static ru.sovcombank.hackaton.proto.DataRow parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static ru.sovcombank.hackaton.proto.DataRow parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static ru.sovcombank.hackaton.proto.DataRow parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static ru.sovcombank.hackaton.proto.DataRow parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static ru.sovcombank.hackaton.proto.DataRow parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static ru.sovcombank.hackaton.proto.DataRow parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(ru.sovcombank.hackaton.proto.DataRow prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code ru.sovcombank.hackaton.proto.DataRow}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:ru.sovcombank.hackaton.proto.DataRow)
      ru.sovcombank.hackaton.proto.DataRowOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return ru.sovcombank.hackaton.proto.DataRowProto.internal_static_ru_sovcombank_hackaton_proto_DataRow_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return ru.sovcombank.hackaton.proto.DataRowProto.internal_static_ru_sovcombank_hackaton_proto_DataRow_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              ru.sovcombank.hackaton.proto.DataRow.class, ru.sovcombank.hackaton.proto.DataRow.Builder.class);
    }

    // Construct using ru.sovcombank.hackaton.proto.DataRow.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      rowIdent_ = "";
      incrementDelete_ = false;
      if (valuesBuilder_ == null) {
        values_ = java.util.Collections.emptyList();
      } else {
        values_ = null;
        valuesBuilder_.clear();
      }
      bitField0_ = (bitField0_ & ~0x00000004);
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return ru.sovcombank.hackaton.proto.DataRowProto.internal_static_ru_sovcombank_hackaton_proto_DataRow_descriptor;
    }

    @java.lang.Override
    public ru.sovcombank.hackaton.proto.DataRow getDefaultInstanceForType() {
      return ru.sovcombank.hackaton.proto.DataRow.getDefaultInstance();
    }

    @java.lang.Override
    public ru.sovcombank.hackaton.proto.DataRow build() {
      ru.sovcombank.hackaton.proto.DataRow result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public ru.sovcombank.hackaton.proto.DataRow buildPartial() {
      ru.sovcombank.hackaton.proto.DataRow result = new ru.sovcombank.hackaton.proto.DataRow(this);
      buildPartialRepeatedFields(result);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartialRepeatedFields(ru.sovcombank.hackaton.proto.DataRow result) {
      if (valuesBuilder_ == null) {
        if (((bitField0_ & 0x00000004) != 0)) {
          values_ = java.util.Collections.unmodifiableList(values_);
          bitField0_ = (bitField0_ & ~0x00000004);
        }
        result.values_ = values_;
      } else {
        result.values_ = valuesBuilder_.build();
      }
    }

    private void buildPartial0(ru.sovcombank.hackaton.proto.DataRow result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.rowIdent_ = rowIdent_;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.incrementDelete_ = incrementDelete_;
      }
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof ru.sovcombank.hackaton.proto.DataRow) {
        return mergeFrom((ru.sovcombank.hackaton.proto.DataRow)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(ru.sovcombank.hackaton.proto.DataRow other) {
      if (other == ru.sovcombank.hackaton.proto.DataRow.getDefaultInstance()) return this;
      if (!other.getRowIdent().isEmpty()) {
        rowIdent_ = other.rowIdent_;
        bitField0_ |= 0x00000001;
        onChanged();
      }
      if (other.getIncrementDelete() != false) {
        setIncrementDelete(other.getIncrementDelete());
      }
      if (valuesBuilder_ == null) {
        if (!other.values_.isEmpty()) {
          if (values_.isEmpty()) {
            values_ = other.values_;
            bitField0_ = (bitField0_ & ~0x00000004);
          } else {
            ensureValuesIsMutable();
            values_.addAll(other.values_);
          }
          onChanged();
        }
      } else {
        if (!other.values_.isEmpty()) {
          if (valuesBuilder_.isEmpty()) {
            valuesBuilder_.dispose();
            valuesBuilder_ = null;
            values_ = other.values_;
            bitField0_ = (bitField0_ & ~0x00000004);
            valuesBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getValuesFieldBuilder() : null;
          } else {
            valuesBuilder_.addAllMessages(other.values_);
          }
        }
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              rowIdent_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000001;
              break;
            } // case 10
            case 16: {
              incrementDelete_ = input.readBool();
              bitField0_ |= 0x00000002;
              break;
            } // case 16
            case 26: {
              ru.sovcombank.hackaton.proto.ValueRef m =
                  input.readMessage(
                      ru.sovcombank.hackaton.proto.ValueRef.parser(),
                      extensionRegistry);
              if (valuesBuilder_ == null) {
                ensureValuesIsMutable();
                values_.add(m);
              } else {
                valuesBuilder_.addMessage(m);
              }
              break;
            } // case 26
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private java.lang.Object rowIdent_ = "";
    /**
     * <pre>
     * Идентификатор записи
     * </pre>
     *
     * <code>string rowIdent = 1;</code>
     * @return The rowIdent.
     */
    public java.lang.String getRowIdent() {
      java.lang.Object ref = rowIdent_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        rowIdent_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * Идентификатор записи
     * </pre>
     *
     * <code>string rowIdent = 1;</code>
     * @return The bytes for rowIdent.
     */
    public com.google.protobuf.ByteString
        getRowIdentBytes() {
      java.lang.Object ref = rowIdent_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        rowIdent_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * Идентификатор записи
     * </pre>
     *
     * <code>string rowIdent = 1;</code>
     * @param value The rowIdent to set.
     * @return This builder for chaining.
     */
    public Builder setRowIdent(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      rowIdent_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Идентификатор записи
     * </pre>
     *
     * <code>string rowIdent = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearRowIdent() {
      rowIdent_ = getDefaultInstance().getRowIdent();
      bitField0_ = (bitField0_ & ~0x00000001);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Идентификатор записи
     * </pre>
     *
     * <code>string rowIdent = 1;</code>
     * @param value The bytes for rowIdent to set.
     * @return This builder for chaining.
     */
    public Builder setRowIdentBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      rowIdent_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }

    private boolean incrementDelete_ ;
    /**
     * <pre>
     * Инкрементальное удаление записи (Удаление записи при инкрементальной передаче данных)
     * </pre>
     *
     * <code>bool incrementDelete = 2;</code>
     * @return The incrementDelete.
     */
    @java.lang.Override
    public boolean getIncrementDelete() {
      return incrementDelete_;
    }
    /**
     * <pre>
     * Инкрементальное удаление записи (Удаление записи при инкрементальной передаче данных)
     * </pre>
     *
     * <code>bool incrementDelete = 2;</code>
     * @param value The incrementDelete to set.
     * @return This builder for chaining.
     */
    public Builder setIncrementDelete(boolean value) {
      
      incrementDelete_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Инкрементальное удаление записи (Удаление записи при инкрементальной передаче данных)
     * </pre>
     *
     * <code>bool incrementDelete = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearIncrementDelete() {
      bitField0_ = (bitField0_ & ~0x00000002);
      incrementDelete_ = false;
      onChanged();
      return this;
    }

    private java.util.List<ru.sovcombank.hackaton.proto.ValueRef> values_ =
      java.util.Collections.emptyList();
    private void ensureValuesIsMutable() {
      if (!((bitField0_ & 0x00000004) != 0)) {
        values_ = new java.util.ArrayList<ru.sovcombank.hackaton.proto.ValueRef>(values_);
        bitField0_ |= 0x00000004;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        ru.sovcombank.hackaton.proto.ValueRef, ru.sovcombank.hackaton.proto.ValueRef.Builder, ru.sovcombank.hackaton.proto.ValueRefOrBuilder> valuesBuilder_;

    /**
     * <pre>
     * Описание значения поля
     * </pre>
     *
     * <code>repeated .ru.sovcombank.hackaton.proto.ValueRef values = 3;</code>
     */
    public java.util.List<ru.sovcombank.hackaton.proto.ValueRef> getValuesList() {
      if (valuesBuilder_ == null) {
        return java.util.Collections.unmodifiableList(values_);
      } else {
        return valuesBuilder_.getMessageList();
      }
    }
    /**
     * <pre>
     * Описание значения поля
     * </pre>
     *
     * <code>repeated .ru.sovcombank.hackaton.proto.ValueRef values = 3;</code>
     */
    public int getValuesCount() {
      if (valuesBuilder_ == null) {
        return values_.size();
      } else {
        return valuesBuilder_.getCount();
      }
    }
    /**
     * <pre>
     * Описание значения поля
     * </pre>
     *
     * <code>repeated .ru.sovcombank.hackaton.proto.ValueRef values = 3;</code>
     */
    public ru.sovcombank.hackaton.proto.ValueRef getValues(int index) {
      if (valuesBuilder_ == null) {
        return values_.get(index);
      } else {
        return valuesBuilder_.getMessage(index);
      }
    }
    /**
     * <pre>
     * Описание значения поля
     * </pre>
     *
     * <code>repeated .ru.sovcombank.hackaton.proto.ValueRef values = 3;</code>
     */
    public Builder setValues(
        int index, ru.sovcombank.hackaton.proto.ValueRef value) {
      if (valuesBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureValuesIsMutable();
        values_.set(index, value);
        onChanged();
      } else {
        valuesBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <pre>
     * Описание значения поля
     * </pre>
     *
     * <code>repeated .ru.sovcombank.hackaton.proto.ValueRef values = 3;</code>
     */
    public Builder setValues(
        int index, ru.sovcombank.hackaton.proto.ValueRef.Builder builderForValue) {
      if (valuesBuilder_ == null) {
        ensureValuesIsMutable();
        values_.set(index, builderForValue.build());
        onChanged();
      } else {
        valuesBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <pre>
     * Описание значения поля
     * </pre>
     *
     * <code>repeated .ru.sovcombank.hackaton.proto.ValueRef values = 3;</code>
     */
    public Builder addValues(ru.sovcombank.hackaton.proto.ValueRef value) {
      if (valuesBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureValuesIsMutable();
        values_.add(value);
        onChanged();
      } else {
        valuesBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <pre>
     * Описание значения поля
     * </pre>
     *
     * <code>repeated .ru.sovcombank.hackaton.proto.ValueRef values = 3;</code>
     */
    public Builder addValues(
        int index, ru.sovcombank.hackaton.proto.ValueRef value) {
      if (valuesBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureValuesIsMutable();
        values_.add(index, value);
        onChanged();
      } else {
        valuesBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <pre>
     * Описание значения поля
     * </pre>
     *
     * <code>repeated .ru.sovcombank.hackaton.proto.ValueRef values = 3;</code>
     */
    public Builder addValues(
        ru.sovcombank.hackaton.proto.ValueRef.Builder builderForValue) {
      if (valuesBuilder_ == null) {
        ensureValuesIsMutable();
        values_.add(builderForValue.build());
        onChanged();
      } else {
        valuesBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <pre>
     * Описание значения поля
     * </pre>
     *
     * <code>repeated .ru.sovcombank.hackaton.proto.ValueRef values = 3;</code>
     */
    public Builder addValues(
        int index, ru.sovcombank.hackaton.proto.ValueRef.Builder builderForValue) {
      if (valuesBuilder_ == null) {
        ensureValuesIsMutable();
        values_.add(index, builderForValue.build());
        onChanged();
      } else {
        valuesBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <pre>
     * Описание значения поля
     * </pre>
     *
     * <code>repeated .ru.sovcombank.hackaton.proto.ValueRef values = 3;</code>
     */
    public Builder addAllValues(
        java.lang.Iterable<? extends ru.sovcombank.hackaton.proto.ValueRef> values) {
      if (valuesBuilder_ == null) {
        ensureValuesIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, values_);
        onChanged();
      } else {
        valuesBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <pre>
     * Описание значения поля
     * </pre>
     *
     * <code>repeated .ru.sovcombank.hackaton.proto.ValueRef values = 3;</code>
     */
    public Builder clearValues() {
      if (valuesBuilder_ == null) {
        values_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000004);
        onChanged();
      } else {
        valuesBuilder_.clear();
      }
      return this;
    }
    /**
     * <pre>
     * Описание значения поля
     * </pre>
     *
     * <code>repeated .ru.sovcombank.hackaton.proto.ValueRef values = 3;</code>
     */
    public Builder removeValues(int index) {
      if (valuesBuilder_ == null) {
        ensureValuesIsMutable();
        values_.remove(index);
        onChanged();
      } else {
        valuesBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <pre>
     * Описание значения поля
     * </pre>
     *
     * <code>repeated .ru.sovcombank.hackaton.proto.ValueRef values = 3;</code>
     */
    public ru.sovcombank.hackaton.proto.ValueRef.Builder getValuesBuilder(
        int index) {
      return getValuesFieldBuilder().getBuilder(index);
    }
    /**
     * <pre>
     * Описание значения поля
     * </pre>
     *
     * <code>repeated .ru.sovcombank.hackaton.proto.ValueRef values = 3;</code>
     */
    public ru.sovcombank.hackaton.proto.ValueRefOrBuilder getValuesOrBuilder(
        int index) {
      if (valuesBuilder_ == null) {
        return values_.get(index);  } else {
        return valuesBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <pre>
     * Описание значения поля
     * </pre>
     *
     * <code>repeated .ru.sovcombank.hackaton.proto.ValueRef values = 3;</code>
     */
    public java.util.List<? extends ru.sovcombank.hackaton.proto.ValueRefOrBuilder> 
         getValuesOrBuilderList() {
      if (valuesBuilder_ != null) {
        return valuesBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(values_);
      }
    }
    /**
     * <pre>
     * Описание значения поля
     * </pre>
     *
     * <code>repeated .ru.sovcombank.hackaton.proto.ValueRef values = 3;</code>
     */
    public ru.sovcombank.hackaton.proto.ValueRef.Builder addValuesBuilder() {
      return getValuesFieldBuilder().addBuilder(
          ru.sovcombank.hackaton.proto.ValueRef.getDefaultInstance());
    }
    /**
     * <pre>
     * Описание значения поля
     * </pre>
     *
     * <code>repeated .ru.sovcombank.hackaton.proto.ValueRef values = 3;</code>
     */
    public ru.sovcombank.hackaton.proto.ValueRef.Builder addValuesBuilder(
        int index) {
      return getValuesFieldBuilder().addBuilder(
          index, ru.sovcombank.hackaton.proto.ValueRef.getDefaultInstance());
    }
    /**
     * <pre>
     * Описание значения поля
     * </pre>
     *
     * <code>repeated .ru.sovcombank.hackaton.proto.ValueRef values = 3;</code>
     */
    public java.util.List<ru.sovcombank.hackaton.proto.ValueRef.Builder> 
         getValuesBuilderList() {
      return getValuesFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        ru.sovcombank.hackaton.proto.ValueRef, ru.sovcombank.hackaton.proto.ValueRef.Builder, ru.sovcombank.hackaton.proto.ValueRefOrBuilder> 
        getValuesFieldBuilder() {
      if (valuesBuilder_ == null) {
        valuesBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            ru.sovcombank.hackaton.proto.ValueRef, ru.sovcombank.hackaton.proto.ValueRef.Builder, ru.sovcombank.hackaton.proto.ValueRefOrBuilder>(
                values_,
                ((bitField0_ & 0x00000004) != 0),
                getParentForChildren(),
                isClean());
        values_ = null;
      }
      return valuesBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:ru.sovcombank.hackaton.proto.DataRow)
  }

  // @@protoc_insertion_point(class_scope:ru.sovcombank.hackaton.proto.DataRow)
  private static final ru.sovcombank.hackaton.proto.DataRow DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new ru.sovcombank.hackaton.proto.DataRow();
  }

  public static ru.sovcombank.hackaton.proto.DataRow getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<DataRow>
      PARSER = new com.google.protobuf.AbstractParser<DataRow>() {
    @java.lang.Override
    public DataRow parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<DataRow> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<DataRow> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public ru.sovcombank.hackaton.proto.DataRow getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

