// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: DataRow.proto

package ru.sovcombank.hackaton.proto;

public final class DataRowProto {
  private DataRowProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ru_sovcombank_hackaton_proto_DataRow_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ru_sovcombank_hackaton_proto_DataRow_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\rDataRow.proto\022\034ru.sovcombank.hackaton." +
      "proto\032\016ValueRef.proto\"l\n\007DataRow\022\020\n\010rowI" +
      "dent\030\001 \001(\t\022\027\n\017incrementDelete\030\002 \001(\010\0226\n\006v" +
      "alues\030\003 \003(\0132&.ru.sovcombank.hackaton.pro" +
      "to.ValueRefB\022B\014DataRowProtoH\001P\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          ru.sovcombank.hackaton.proto.ValueRefProto.getDescriptor(),
        });
    internal_static_ru_sovcombank_hackaton_proto_DataRow_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_ru_sovcombank_hackaton_proto_DataRow_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ru_sovcombank_hackaton_proto_DataRow_descriptor,
        new java.lang.String[] { "RowIdent", "IncrementDelete", "Values", });
    ru.sovcombank.hackaton.proto.ValueRefProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
