// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Event.proto

package ru.sovcombank.hackaton.proto;

public interface EventOrBuilder extends
    // @@protoc_insertion_point(interface_extends:ru.sovcombank.hackaton.proto.Event)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * Статус
   * </pre>
   *
   * <code>.ru.sovcombank.hackaton.proto.Status status = 1;</code>
   * @return Whether the status field is set.
   */
  boolean hasStatus();
  /**
   * <pre>
   * Статус
   * </pre>
   *
   * <code>.ru.sovcombank.hackaton.proto.Status status = 1;</code>
   * @return The status.
   */
  ru.sovcombank.hackaton.proto.Status getStatus();
  /**
   * <pre>
   * Статус
   * </pre>
   *
   * <code>.ru.sovcombank.hackaton.proto.Status status = 1;</code>
   */
  ru.sovcombank.hackaton.proto.StatusOrBuilder getStatusOrBuilder();
}
