// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ExchangeInfoMessage.proto

package ru.sovcombank.hackaton.proto;

public final class ExchangeInfoMessageProto {
  private ExchangeInfoMessageProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ru_sovcombank_hackaton_proto_ExchangeInfoMessage_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ru_sovcombank_hackaton_proto_ExchangeInfoMessage_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\031ExchangeInfoMessage.proto\022\034ru.sovcomba" +
      "nk.hackaton.proto\032\014Header.proto\032\rRequest" +
      ".proto\032\016Response.proto\032\013Event.proto\"\377\001\n\023" +
      "ExchangeInfoMessage\0224\n\006header\030\001 \001(\0132$.ru" +
      ".sovcombank.hackaton.proto.Header\0228\n\007req" +
      "uest\030\002 \001(\0132%.ru.sovcombank.hackaton.prot" +
      "o.RequestH\000\022:\n\010response\030\003 \001(\0132&.ru.sovco" +
      "mbank.hackaton.proto.ResponseH\000\0224\n\005event" +
      "\030\004 \001(\0132#.ru.sovcombank.hackaton.proto.Ev" +
      "entH\000B\006\n\004bodyB\036B\030ExchangeInfoMessageProt" +
      "oH\001P\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          ru.sovcombank.hackaton.proto.HeaderProto.getDescriptor(),
          ru.sovcombank.hackaton.proto.RequestProto.getDescriptor(),
          ru.sovcombank.hackaton.proto.ResponseProto.getDescriptor(),
          ru.sovcombank.hackaton.proto.EventProto.getDescriptor(),
        });
    internal_static_ru_sovcombank_hackaton_proto_ExchangeInfoMessage_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_ru_sovcombank_hackaton_proto_ExchangeInfoMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ru_sovcombank_hackaton_proto_ExchangeInfoMessage_descriptor,
        new java.lang.String[] { "Header", "Request", "Response", "Event", "Body", });
    ru.sovcombank.hackaton.proto.HeaderProto.getDescriptor();
    ru.sovcombank.hackaton.proto.RequestProto.getDescriptor();
    ru.sovcombank.hackaton.proto.ResponseProto.getDescriptor();
    ru.sovcombank.hackaton.proto.EventProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
