// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Header.proto

package ru.sovcombank.hackaton.proto;

/**
 * <pre>
 **
 *Заголовок сообщения.
 *Поля: messageNum, timestamp, sender, receiver - не должны быть пустыми.
 *Поле  messageNumAnswer - заполняется на основании поля messageNum сообщения на которое формируется ответ.
 *Данное поле заполняется только для сообщений response.
 * </pre>
 *
 * Protobuf type {@code ru.sovcombank.hackaton.proto.Header}
 */
public final class Header extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:ru.sovcombank.hackaton.proto.Header)
    HeaderOrBuilder {
private static final long serialVersionUID = 0L;
  // Use Header.newBuilder() to construct.
  private Header(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private Header() {
    messageNum_ = "";
    sender_ = "";
    receiver_ = "";
    messageNumAnswer_ = "";
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new Header();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return ru.sovcombank.hackaton.proto.HeaderProto.internal_static_ru_sovcombank_hackaton_proto_Header_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return ru.sovcombank.hackaton.proto.HeaderProto.internal_static_ru_sovcombank_hackaton_proto_Header_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            ru.sovcombank.hackaton.proto.Header.class, ru.sovcombank.hackaton.proto.Header.Builder.class);
  }

  private int bitField0_;
  public static final int MESSAGENUM_FIELD_NUMBER = 1;
  @SuppressWarnings("serial")
  private volatile java.lang.Object messageNum_ = "";
  /**
   * <pre>
   * Номер сообщения
   * </pre>
   *
   * <code>string messageNum = 1;</code>
   * @return The messageNum.
   */
  @java.lang.Override
  public java.lang.String getMessageNum() {
    java.lang.Object ref = messageNum_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      messageNum_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * Номер сообщения
   * </pre>
   *
   * <code>string messageNum = 1;</code>
   * @return The bytes for messageNum.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getMessageNumBytes() {
    java.lang.Object ref = messageNum_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      messageNum_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int TIMESTAMP_FIELD_NUMBER = 2;
  private long timestamp_ = 0L;
  /**
   * <pre>
   * Время создания сообщения в миллисекундах от начала эпохи.
   * </pre>
   *
   * <code>int64 timestamp = 2;</code>
   * @return The timestamp.
   */
  @java.lang.Override
  public long getTimestamp() {
    return timestamp_;
  }

  public static final int SENDER_FIELD_NUMBER = 3;
  @SuppressWarnings("serial")
  private volatile java.lang.Object sender_ = "";
  /**
   * <pre>
   * Идентификатор отправителя
   * </pre>
   *
   * <code>string sender = 3;</code>
   * @return The sender.
   */
  @java.lang.Override
  public java.lang.String getSender() {
    java.lang.Object ref = sender_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      sender_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * Идентификатор отправителя
   * </pre>
   *
   * <code>string sender = 3;</code>
   * @return The bytes for sender.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getSenderBytes() {
    java.lang.Object ref = sender_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      sender_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int RECEIVER_FIELD_NUMBER = 4;
  @SuppressWarnings("serial")
  private volatile java.lang.Object receiver_ = "";
  /**
   * <pre>
   * Идентификатор получателя
   * </pre>
   *
   * <code>string receiver = 4;</code>
   * @return The receiver.
   */
  @java.lang.Override
  public java.lang.String getReceiver() {
    java.lang.Object ref = receiver_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      receiver_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * Идентификатор получателя
   * </pre>
   *
   * <code>string receiver = 4;</code>
   * @return The bytes for receiver.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getReceiverBytes() {
    java.lang.Object ref = receiver_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      receiver_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int MESSAGENUMANSWER_FIELD_NUMBER = 5;
  @SuppressWarnings("serial")
  private volatile java.lang.Object messageNumAnswer_ = "";
  /**
   * <pre>
   * Номер сообщения на которое сформирован ответ
   * </pre>
   *
   * <code>optional string messageNumAnswer = 5;</code>
   * @return Whether the messageNumAnswer field is set.
   */
  @java.lang.Override
  public boolean hasMessageNumAnswer() {
    return ((bitField0_ & 0x00000001) != 0);
  }
  /**
   * <pre>
   * Номер сообщения на которое сформирован ответ
   * </pre>
   *
   * <code>optional string messageNumAnswer = 5;</code>
   * @return The messageNumAnswer.
   */
  @java.lang.Override
  public java.lang.String getMessageNumAnswer() {
    java.lang.Object ref = messageNumAnswer_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      messageNumAnswer_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * Номер сообщения на которое сформирован ответ
   * </pre>
   *
   * <code>optional string messageNumAnswer = 5;</code>
   * @return The bytes for messageNumAnswer.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getMessageNumAnswerBytes() {
    java.lang.Object ref = messageNumAnswer_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      messageNumAnswer_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(messageNum_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, messageNum_);
    }
    if (timestamp_ != 0L) {
      output.writeInt64(2, timestamp_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(sender_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 3, sender_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(receiver_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 4, receiver_);
    }
    if (((bitField0_ & 0x00000001) != 0)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 5, messageNumAnswer_);
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(messageNum_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, messageNum_);
    }
    if (timestamp_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(2, timestamp_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(sender_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, sender_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(receiver_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, receiver_);
    }
    if (((bitField0_ & 0x00000001) != 0)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, messageNumAnswer_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof ru.sovcombank.hackaton.proto.Header)) {
      return super.equals(obj);
    }
    ru.sovcombank.hackaton.proto.Header other = (ru.sovcombank.hackaton.proto.Header) obj;

    if (!getMessageNum()
        .equals(other.getMessageNum())) return false;
    if (getTimestamp()
        != other.getTimestamp()) return false;
    if (!getSender()
        .equals(other.getSender())) return false;
    if (!getReceiver()
        .equals(other.getReceiver())) return false;
    if (hasMessageNumAnswer() != other.hasMessageNumAnswer()) return false;
    if (hasMessageNumAnswer()) {
      if (!getMessageNumAnswer()
          .equals(other.getMessageNumAnswer())) return false;
    }
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + MESSAGENUM_FIELD_NUMBER;
    hash = (53 * hash) + getMessageNum().hashCode();
    hash = (37 * hash) + TIMESTAMP_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getTimestamp());
    hash = (37 * hash) + SENDER_FIELD_NUMBER;
    hash = (53 * hash) + getSender().hashCode();
    hash = (37 * hash) + RECEIVER_FIELD_NUMBER;
    hash = (53 * hash) + getReceiver().hashCode();
    if (hasMessageNumAnswer()) {
      hash = (37 * hash) + MESSAGENUMANSWER_FIELD_NUMBER;
      hash = (53 * hash) + getMessageNumAnswer().hashCode();
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static ru.sovcombank.hackaton.proto.Header parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static ru.sovcombank.hackaton.proto.Header parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static ru.sovcombank.hackaton.proto.Header parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static ru.sovcombank.hackaton.proto.Header parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static ru.sovcombank.hackaton.proto.Header parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static ru.sovcombank.hackaton.proto.Header parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static ru.sovcombank.hackaton.proto.Header parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static ru.sovcombank.hackaton.proto.Header parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static ru.sovcombank.hackaton.proto.Header parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static ru.sovcombank.hackaton.proto.Header parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static ru.sovcombank.hackaton.proto.Header parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static ru.sovcombank.hackaton.proto.Header parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(ru.sovcombank.hackaton.proto.Header prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   **
   *Заголовок сообщения.
   *Поля: messageNum, timestamp, sender, receiver - не должны быть пустыми.
   *Поле  messageNumAnswer - заполняется на основании поля messageNum сообщения на которое формируется ответ.
   *Данное поле заполняется только для сообщений response.
   * </pre>
   *
   * Protobuf type {@code ru.sovcombank.hackaton.proto.Header}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:ru.sovcombank.hackaton.proto.Header)
      ru.sovcombank.hackaton.proto.HeaderOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return ru.sovcombank.hackaton.proto.HeaderProto.internal_static_ru_sovcombank_hackaton_proto_Header_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return ru.sovcombank.hackaton.proto.HeaderProto.internal_static_ru_sovcombank_hackaton_proto_Header_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              ru.sovcombank.hackaton.proto.Header.class, ru.sovcombank.hackaton.proto.Header.Builder.class);
    }

    // Construct using ru.sovcombank.hackaton.proto.Header.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      messageNum_ = "";
      timestamp_ = 0L;
      sender_ = "";
      receiver_ = "";
      messageNumAnswer_ = "";
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return ru.sovcombank.hackaton.proto.HeaderProto.internal_static_ru_sovcombank_hackaton_proto_Header_descriptor;
    }

    @java.lang.Override
    public ru.sovcombank.hackaton.proto.Header getDefaultInstanceForType() {
      return ru.sovcombank.hackaton.proto.Header.getDefaultInstance();
    }

    @java.lang.Override
    public ru.sovcombank.hackaton.proto.Header build() {
      ru.sovcombank.hackaton.proto.Header result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public ru.sovcombank.hackaton.proto.Header buildPartial() {
      ru.sovcombank.hackaton.proto.Header result = new ru.sovcombank.hackaton.proto.Header(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(ru.sovcombank.hackaton.proto.Header result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.messageNum_ = messageNum_;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.timestamp_ = timestamp_;
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.sender_ = sender_;
      }
      if (((from_bitField0_ & 0x00000008) != 0)) {
        result.receiver_ = receiver_;
      }
      int to_bitField0_ = 0;
      if (((from_bitField0_ & 0x00000010) != 0)) {
        result.messageNumAnswer_ = messageNumAnswer_;
        to_bitField0_ |= 0x00000001;
      }
      result.bitField0_ |= to_bitField0_;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof ru.sovcombank.hackaton.proto.Header) {
        return mergeFrom((ru.sovcombank.hackaton.proto.Header)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(ru.sovcombank.hackaton.proto.Header other) {
      if (other == ru.sovcombank.hackaton.proto.Header.getDefaultInstance()) return this;
      if (!other.getMessageNum().isEmpty()) {
        messageNum_ = other.messageNum_;
        bitField0_ |= 0x00000001;
        onChanged();
      }
      if (other.getTimestamp() != 0L) {
        setTimestamp(other.getTimestamp());
      }
      if (!other.getSender().isEmpty()) {
        sender_ = other.sender_;
        bitField0_ |= 0x00000004;
        onChanged();
      }
      if (!other.getReceiver().isEmpty()) {
        receiver_ = other.receiver_;
        bitField0_ |= 0x00000008;
        onChanged();
      }
      if (other.hasMessageNumAnswer()) {
        messageNumAnswer_ = other.messageNumAnswer_;
        bitField0_ |= 0x00000010;
        onChanged();
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              messageNum_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000001;
              break;
            } // case 10
            case 16: {
              timestamp_ = input.readInt64();
              bitField0_ |= 0x00000002;
              break;
            } // case 16
            case 26: {
              sender_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000004;
              break;
            } // case 26
            case 34: {
              receiver_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000008;
              break;
            } // case 34
            case 42: {
              messageNumAnswer_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000010;
              break;
            } // case 42
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private java.lang.Object messageNum_ = "";
    /**
     * <pre>
     * Номер сообщения
     * </pre>
     *
     * <code>string messageNum = 1;</code>
     * @return The messageNum.
     */
    public java.lang.String getMessageNum() {
      java.lang.Object ref = messageNum_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        messageNum_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * Номер сообщения
     * </pre>
     *
     * <code>string messageNum = 1;</code>
     * @return The bytes for messageNum.
     */
    public com.google.protobuf.ByteString
        getMessageNumBytes() {
      java.lang.Object ref = messageNum_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        messageNum_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * Номер сообщения
     * </pre>
     *
     * <code>string messageNum = 1;</code>
     * @param value The messageNum to set.
     * @return This builder for chaining.
     */
    public Builder setMessageNum(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      messageNum_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Номер сообщения
     * </pre>
     *
     * <code>string messageNum = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearMessageNum() {
      messageNum_ = getDefaultInstance().getMessageNum();
      bitField0_ = (bitField0_ & ~0x00000001);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Номер сообщения
     * </pre>
     *
     * <code>string messageNum = 1;</code>
     * @param value The bytes for messageNum to set.
     * @return This builder for chaining.
     */
    public Builder setMessageNumBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      messageNum_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }

    private long timestamp_ ;
    /**
     * <pre>
     * Время создания сообщения в миллисекундах от начала эпохи.
     * </pre>
     *
     * <code>int64 timestamp = 2;</code>
     * @return The timestamp.
     */
    @java.lang.Override
    public long getTimestamp() {
      return timestamp_;
    }
    /**
     * <pre>
     * Время создания сообщения в миллисекундах от начала эпохи.
     * </pre>
     *
     * <code>int64 timestamp = 2;</code>
     * @param value The timestamp to set.
     * @return This builder for chaining.
     */
    public Builder setTimestamp(long value) {
      
      timestamp_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Время создания сообщения в миллисекундах от начала эпохи.
     * </pre>
     *
     * <code>int64 timestamp = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearTimestamp() {
      bitField0_ = (bitField0_ & ~0x00000002);
      timestamp_ = 0L;
      onChanged();
      return this;
    }

    private java.lang.Object sender_ = "";
    /**
     * <pre>
     * Идентификатор отправителя
     * </pre>
     *
     * <code>string sender = 3;</code>
     * @return The sender.
     */
    public java.lang.String getSender() {
      java.lang.Object ref = sender_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        sender_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * Идентификатор отправителя
     * </pre>
     *
     * <code>string sender = 3;</code>
     * @return The bytes for sender.
     */
    public com.google.protobuf.ByteString
        getSenderBytes() {
      java.lang.Object ref = sender_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        sender_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * Идентификатор отправителя
     * </pre>
     *
     * <code>string sender = 3;</code>
     * @param value The sender to set.
     * @return This builder for chaining.
     */
    public Builder setSender(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      sender_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Идентификатор отправителя
     * </pre>
     *
     * <code>string sender = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearSender() {
      sender_ = getDefaultInstance().getSender();
      bitField0_ = (bitField0_ & ~0x00000004);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Идентификатор отправителя
     * </pre>
     *
     * <code>string sender = 3;</code>
     * @param value The bytes for sender to set.
     * @return This builder for chaining.
     */
    public Builder setSenderBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      sender_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }

    private java.lang.Object receiver_ = "";
    /**
     * <pre>
     * Идентификатор получателя
     * </pre>
     *
     * <code>string receiver = 4;</code>
     * @return The receiver.
     */
    public java.lang.String getReceiver() {
      java.lang.Object ref = receiver_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        receiver_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * Идентификатор получателя
     * </pre>
     *
     * <code>string receiver = 4;</code>
     * @return The bytes for receiver.
     */
    public com.google.protobuf.ByteString
        getReceiverBytes() {
      java.lang.Object ref = receiver_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        receiver_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * Идентификатор получателя
     * </pre>
     *
     * <code>string receiver = 4;</code>
     * @param value The receiver to set.
     * @return This builder for chaining.
     */
    public Builder setReceiver(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      receiver_ = value;
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Идентификатор получателя
     * </pre>
     *
     * <code>string receiver = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearReceiver() {
      receiver_ = getDefaultInstance().getReceiver();
      bitField0_ = (bitField0_ & ~0x00000008);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Идентификатор получателя
     * </pre>
     *
     * <code>string receiver = 4;</code>
     * @param value The bytes for receiver to set.
     * @return This builder for chaining.
     */
    public Builder setReceiverBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      receiver_ = value;
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }

    private java.lang.Object messageNumAnswer_ = "";
    /**
     * <pre>
     * Номер сообщения на которое сформирован ответ
     * </pre>
     *
     * <code>optional string messageNumAnswer = 5;</code>
     * @return Whether the messageNumAnswer field is set.
     */
    public boolean hasMessageNumAnswer() {
      return ((bitField0_ & 0x00000010) != 0);
    }
    /**
     * <pre>
     * Номер сообщения на которое сформирован ответ
     * </pre>
     *
     * <code>optional string messageNumAnswer = 5;</code>
     * @return The messageNumAnswer.
     */
    public java.lang.String getMessageNumAnswer() {
      java.lang.Object ref = messageNumAnswer_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        messageNumAnswer_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * Номер сообщения на которое сформирован ответ
     * </pre>
     *
     * <code>optional string messageNumAnswer = 5;</code>
     * @return The bytes for messageNumAnswer.
     */
    public com.google.protobuf.ByteString
        getMessageNumAnswerBytes() {
      java.lang.Object ref = messageNumAnswer_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        messageNumAnswer_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * Номер сообщения на которое сформирован ответ
     * </pre>
     *
     * <code>optional string messageNumAnswer = 5;</code>
     * @param value The messageNumAnswer to set.
     * @return This builder for chaining.
     */
    public Builder setMessageNumAnswer(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      messageNumAnswer_ = value;
      bitField0_ |= 0x00000010;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Номер сообщения на которое сформирован ответ
     * </pre>
     *
     * <code>optional string messageNumAnswer = 5;</code>
     * @return This builder for chaining.
     */
    public Builder clearMessageNumAnswer() {
      messageNumAnswer_ = getDefaultInstance().getMessageNumAnswer();
      bitField0_ = (bitField0_ & ~0x00000010);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Номер сообщения на которое сформирован ответ
     * </pre>
     *
     * <code>optional string messageNumAnswer = 5;</code>
     * @param value The bytes for messageNumAnswer to set.
     * @return This builder for chaining.
     */
    public Builder setMessageNumAnswerBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      messageNumAnswer_ = value;
      bitField0_ |= 0x00000010;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:ru.sovcombank.hackaton.proto.Header)
  }

  // @@protoc_insertion_point(class_scope:ru.sovcombank.hackaton.proto.Header)
  private static final ru.sovcombank.hackaton.proto.Header DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new ru.sovcombank.hackaton.proto.Header();
  }

  public static ru.sovcombank.hackaton.proto.Header getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<Header>
      PARSER = new com.google.protobuf.AbstractParser<Header>() {
    @java.lang.Override
    public Header parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<Header> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<Header> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public ru.sovcombank.hackaton.proto.Header getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

