// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Header.proto

package ru.sovcombank.hackaton.proto;

public final class HeaderProto {
  private HeaderProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ru_sovcombank_hackaton_proto_Header_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ru_sovcombank_hackaton_proto_Header_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\014Header.proto\022\034ru.sovcombank.hackaton.p" +
      "roto\"\205\001\n\006Header\022\022\n\nmessageNum\030\001 \001(\t\022\021\n\tt" +
      "imestamp\030\002 \001(\003\022\016\n\006sender\030\003 \001(\t\022\020\n\010receiv" +
      "er\030\004 \001(\t\022\035\n\020messageNumAnswer\030\005 \001(\tH\000\210\001\001B" +
      "\023\n\021_messageNumAnswerB\021B\013HeaderProtoH\001P\001b" +
      "\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_ru_sovcombank_hackaton_proto_Header_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_ru_sovcombank_hackaton_proto_Header_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ru_sovcombank_hackaton_proto_Header_descriptor,
        new java.lang.String[] { "MessageNum", "Timestamp", "Sender", "Receiver", "MessageNumAnswer", "MessageNumAnswer", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
