// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: OwnCommand.proto

package ru.sovcombank.hackaton.proto;

public interface OwnCommandOrBuilder extends
    // @@protoc_insertion_point(interface_extends:ru.sovcombank.hackaton.proto.OwnCommand)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * Идентификатор команды
   * </pre>
   *
   * <code>string alias = 1;</code>
   * @return The alias.
   */
  java.lang.String getAlias();
  /**
   * <pre>
   * Идентификатор команды
   * </pre>
   *
   * <code>string alias = 1;</code>
   * @return The bytes for alias.
   */
  com.google.protobuf.ByteString
      getAliasBytes();

  /**
   * <pre>
   * Заголовок команды
   * </pre>
   *
   * <code>optional string caption = 2;</code>
   * @return Whether the caption field is set.
   */
  boolean hasCaption();
  /**
   * <pre>
   * Заголовок команды
   * </pre>
   *
   * <code>optional string caption = 2;</code>
   * @return The caption.
   */
  java.lang.String getCaption();
  /**
   * <pre>
   * Заголовок команды
   * </pre>
   *
   * <code>optional string caption = 2;</code>
   * @return The bytes for caption.
   */
  com.google.protobuf.ByteString
      getCaptionBytes();

  /**
   * <pre>
   * Описание команды
   * </pre>
   *
   * <code>optional string description = 3;</code>
   * @return Whether the description field is set.
   */
  boolean hasDescription();
  /**
   * <pre>
   * Описание команды
   * </pre>
   *
   * <code>optional string description = 3;</code>
   * @return The description.
   */
  java.lang.String getDescription();
  /**
   * <pre>
   * Описание команды
   * </pre>
   *
   * <code>optional string description = 3;</code>
   * @return The bytes for description.
   */
  com.google.protobuf.ByteString
      getDescriptionBytes();

  /**
   * <pre>
   * Список параметров для команды
   * </pre>
   *
   * <code>repeated .ru.sovcombank.hackaton.proto.Parameter parameters = 4;</code>
   */
  java.util.List<ru.sovcombank.hackaton.proto.Parameter> 
      getParametersList();
  /**
   * <pre>
   * Список параметров для команды
   * </pre>
   *
   * <code>repeated .ru.sovcombank.hackaton.proto.Parameter parameters = 4;</code>
   */
  ru.sovcombank.hackaton.proto.Parameter getParameters(int index);
  /**
   * <pre>
   * Список параметров для команды
   * </pre>
   *
   * <code>repeated .ru.sovcombank.hackaton.proto.Parameter parameters = 4;</code>
   */
  int getParametersCount();
  /**
   * <pre>
   * Список параметров для команды
   * </pre>
   *
   * <code>repeated .ru.sovcombank.hackaton.proto.Parameter parameters = 4;</code>
   */
  java.util.List<? extends ru.sovcombank.hackaton.proto.ParameterOrBuilder> 
      getParametersOrBuilderList();
  /**
   * <pre>
   * Список параметров для команды
   * </pre>
   *
   * <code>repeated .ru.sovcombank.hackaton.proto.Parameter parameters = 4;</code>
   */
  ru.sovcombank.hackaton.proto.ParameterOrBuilder getParametersOrBuilder(
      int index);
}
