// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: OwnCommand.proto

package ru.sovcombank.hackaton.proto;

/**
 * Protobuf type {@code ru.sovcombank.hackaton.proto.OwnCommand}
 */
public final class OwnCommand extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:ru.sovcombank.hackaton.proto.OwnCommand)
    OwnCommandOrBuilder {
private static final long serialVersionUID = 0L;
  // Use OwnCommand.newBuilder() to construct.
  private OwnCommand(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private OwnCommand() {
    alias_ = "";
    caption_ = "";
    description_ = "";
    parameters_ = java.util.Collections.emptyList();
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new OwnCommand();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return ru.sovcombank.hackaton.proto.OwnCommandProto.internal_static_ru_sovcombank_hackaton_proto_OwnCommand_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return ru.sovcombank.hackaton.proto.OwnCommandProto.internal_static_ru_sovcombank_hackaton_proto_OwnCommand_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            ru.sovcombank.hackaton.proto.OwnCommand.class, ru.sovcombank.hackaton.proto.OwnCommand.Builder.class);
  }

  private int bitField0_;
  public static final int ALIAS_FIELD_NUMBER = 1;
  @SuppressWarnings("serial")
  private volatile java.lang.Object alias_ = "";
  /**
   * <pre>
   * Идентификатор команды
   * </pre>
   *
   * <code>string alias = 1;</code>
   * @return The alias.
   */
  @java.lang.Override
  public java.lang.String getAlias() {
    java.lang.Object ref = alias_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      alias_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * Идентификатор команды
   * </pre>
   *
   * <code>string alias = 1;</code>
   * @return The bytes for alias.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getAliasBytes() {
    java.lang.Object ref = alias_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      alias_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int CAPTION_FIELD_NUMBER = 2;
  @SuppressWarnings("serial")
  private volatile java.lang.Object caption_ = "";
  /**
   * <pre>
   * Заголовок команды
   * </pre>
   *
   * <code>optional string caption = 2;</code>
   * @return Whether the caption field is set.
   */
  @java.lang.Override
  public boolean hasCaption() {
    return ((bitField0_ & 0x00000001) != 0);
  }
  /**
   * <pre>
   * Заголовок команды
   * </pre>
   *
   * <code>optional string caption = 2;</code>
   * @return The caption.
   */
  @java.lang.Override
  public java.lang.String getCaption() {
    java.lang.Object ref = caption_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      caption_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * Заголовок команды
   * </pre>
   *
   * <code>optional string caption = 2;</code>
   * @return The bytes for caption.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getCaptionBytes() {
    java.lang.Object ref = caption_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      caption_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int DESCRIPTION_FIELD_NUMBER = 3;
  @SuppressWarnings("serial")
  private volatile java.lang.Object description_ = "";
  /**
   * <pre>
   * Описание команды
   * </pre>
   *
   * <code>optional string description = 3;</code>
   * @return Whether the description field is set.
   */
  @java.lang.Override
  public boolean hasDescription() {
    return ((bitField0_ & 0x00000002) != 0);
  }
  /**
   * <pre>
   * Описание команды
   * </pre>
   *
   * <code>optional string description = 3;</code>
   * @return The description.
   */
  @java.lang.Override
  public java.lang.String getDescription() {
    java.lang.Object ref = description_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      description_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * Описание команды
   * </pre>
   *
   * <code>optional string description = 3;</code>
   * @return The bytes for description.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getDescriptionBytes() {
    java.lang.Object ref = description_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      description_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int PARAMETERS_FIELD_NUMBER = 4;
  @SuppressWarnings("serial")
  private java.util.List<ru.sovcombank.hackaton.proto.Parameter> parameters_;
  /**
   * <pre>
   * Список параметров для команды
   * </pre>
   *
   * <code>repeated .ru.sovcombank.hackaton.proto.Parameter parameters = 4;</code>
   */
  @java.lang.Override
  public java.util.List<ru.sovcombank.hackaton.proto.Parameter> getParametersList() {
    return parameters_;
  }
  /**
   * <pre>
   * Список параметров для команды
   * </pre>
   *
   * <code>repeated .ru.sovcombank.hackaton.proto.Parameter parameters = 4;</code>
   */
  @java.lang.Override
  public java.util.List<? extends ru.sovcombank.hackaton.proto.ParameterOrBuilder> 
      getParametersOrBuilderList() {
    return parameters_;
  }
  /**
   * <pre>
   * Список параметров для команды
   * </pre>
   *
   * <code>repeated .ru.sovcombank.hackaton.proto.Parameter parameters = 4;</code>
   */
  @java.lang.Override
  public int getParametersCount() {
    return parameters_.size();
  }
  /**
   * <pre>
   * Список параметров для команды
   * </pre>
   *
   * <code>repeated .ru.sovcombank.hackaton.proto.Parameter parameters = 4;</code>
   */
  @java.lang.Override
  public ru.sovcombank.hackaton.proto.Parameter getParameters(int index) {
    return parameters_.get(index);
  }
  /**
   * <pre>
   * Список параметров для команды
   * </pre>
   *
   * <code>repeated .ru.sovcombank.hackaton.proto.Parameter parameters = 4;</code>
   */
  @java.lang.Override
  public ru.sovcombank.hackaton.proto.ParameterOrBuilder getParametersOrBuilder(
      int index) {
    return parameters_.get(index);
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(alias_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, alias_);
    }
    if (((bitField0_ & 0x00000001) != 0)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, caption_);
    }
    if (((bitField0_ & 0x00000002) != 0)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 3, description_);
    }
    for (int i = 0; i < parameters_.size(); i++) {
      output.writeMessage(4, parameters_.get(i));
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(alias_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, alias_);
    }
    if (((bitField0_ & 0x00000001) != 0)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, caption_);
    }
    if (((bitField0_ & 0x00000002) != 0)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, description_);
    }
    for (int i = 0; i < parameters_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(4, parameters_.get(i));
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof ru.sovcombank.hackaton.proto.OwnCommand)) {
      return super.equals(obj);
    }
    ru.sovcombank.hackaton.proto.OwnCommand other = (ru.sovcombank.hackaton.proto.OwnCommand) obj;

    if (!getAlias()
        .equals(other.getAlias())) return false;
    if (hasCaption() != other.hasCaption()) return false;
    if (hasCaption()) {
      if (!getCaption()
          .equals(other.getCaption())) return false;
    }
    if (hasDescription() != other.hasDescription()) return false;
    if (hasDescription()) {
      if (!getDescription()
          .equals(other.getDescription())) return false;
    }
    if (!getParametersList()
        .equals(other.getParametersList())) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + ALIAS_FIELD_NUMBER;
    hash = (53 * hash) + getAlias().hashCode();
    if (hasCaption()) {
      hash = (37 * hash) + CAPTION_FIELD_NUMBER;
      hash = (53 * hash) + getCaption().hashCode();
    }
    if (hasDescription()) {
      hash = (37 * hash) + DESCRIPTION_FIELD_NUMBER;
      hash = (53 * hash) + getDescription().hashCode();
    }
    if (getParametersCount() > 0) {
      hash = (37 * hash) + PARAMETERS_FIELD_NUMBER;
      hash = (53 * hash) + getParametersList().hashCode();
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static ru.sovcombank.hackaton.proto.OwnCommand parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static ru.sovcombank.hackaton.proto.OwnCommand parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static ru.sovcombank.hackaton.proto.OwnCommand parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static ru.sovcombank.hackaton.proto.OwnCommand parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static ru.sovcombank.hackaton.proto.OwnCommand parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static ru.sovcombank.hackaton.proto.OwnCommand parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static ru.sovcombank.hackaton.proto.OwnCommand parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static ru.sovcombank.hackaton.proto.OwnCommand parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static ru.sovcombank.hackaton.proto.OwnCommand parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static ru.sovcombank.hackaton.proto.OwnCommand parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static ru.sovcombank.hackaton.proto.OwnCommand parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static ru.sovcombank.hackaton.proto.OwnCommand parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(ru.sovcombank.hackaton.proto.OwnCommand prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code ru.sovcombank.hackaton.proto.OwnCommand}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:ru.sovcombank.hackaton.proto.OwnCommand)
      ru.sovcombank.hackaton.proto.OwnCommandOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return ru.sovcombank.hackaton.proto.OwnCommandProto.internal_static_ru_sovcombank_hackaton_proto_OwnCommand_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return ru.sovcombank.hackaton.proto.OwnCommandProto.internal_static_ru_sovcombank_hackaton_proto_OwnCommand_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              ru.sovcombank.hackaton.proto.OwnCommand.class, ru.sovcombank.hackaton.proto.OwnCommand.Builder.class);
    }

    // Construct using ru.sovcombank.hackaton.proto.OwnCommand.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      alias_ = "";
      caption_ = "";
      description_ = "";
      if (parametersBuilder_ == null) {
        parameters_ = java.util.Collections.emptyList();
      } else {
        parameters_ = null;
        parametersBuilder_.clear();
      }
      bitField0_ = (bitField0_ & ~0x00000008);
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return ru.sovcombank.hackaton.proto.OwnCommandProto.internal_static_ru_sovcombank_hackaton_proto_OwnCommand_descriptor;
    }

    @java.lang.Override
    public ru.sovcombank.hackaton.proto.OwnCommand getDefaultInstanceForType() {
      return ru.sovcombank.hackaton.proto.OwnCommand.getDefaultInstance();
    }

    @java.lang.Override
    public ru.sovcombank.hackaton.proto.OwnCommand build() {
      ru.sovcombank.hackaton.proto.OwnCommand result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public ru.sovcombank.hackaton.proto.OwnCommand buildPartial() {
      ru.sovcombank.hackaton.proto.OwnCommand result = new ru.sovcombank.hackaton.proto.OwnCommand(this);
      buildPartialRepeatedFields(result);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartialRepeatedFields(ru.sovcombank.hackaton.proto.OwnCommand result) {
      if (parametersBuilder_ == null) {
        if (((bitField0_ & 0x00000008) != 0)) {
          parameters_ = java.util.Collections.unmodifiableList(parameters_);
          bitField0_ = (bitField0_ & ~0x00000008);
        }
        result.parameters_ = parameters_;
      } else {
        result.parameters_ = parametersBuilder_.build();
      }
    }

    private void buildPartial0(ru.sovcombank.hackaton.proto.OwnCommand result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.alias_ = alias_;
      }
      int to_bitField0_ = 0;
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.caption_ = caption_;
        to_bitField0_ |= 0x00000001;
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.description_ = description_;
        to_bitField0_ |= 0x00000002;
      }
      result.bitField0_ |= to_bitField0_;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof ru.sovcombank.hackaton.proto.OwnCommand) {
        return mergeFrom((ru.sovcombank.hackaton.proto.OwnCommand)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(ru.sovcombank.hackaton.proto.OwnCommand other) {
      if (other == ru.sovcombank.hackaton.proto.OwnCommand.getDefaultInstance()) return this;
      if (!other.getAlias().isEmpty()) {
        alias_ = other.alias_;
        bitField0_ |= 0x00000001;
        onChanged();
      }
      if (other.hasCaption()) {
        caption_ = other.caption_;
        bitField0_ |= 0x00000002;
        onChanged();
      }
      if (other.hasDescription()) {
        description_ = other.description_;
        bitField0_ |= 0x00000004;
        onChanged();
      }
      if (parametersBuilder_ == null) {
        if (!other.parameters_.isEmpty()) {
          if (parameters_.isEmpty()) {
            parameters_ = other.parameters_;
            bitField0_ = (bitField0_ & ~0x00000008);
          } else {
            ensureParametersIsMutable();
            parameters_.addAll(other.parameters_);
          }
          onChanged();
        }
      } else {
        if (!other.parameters_.isEmpty()) {
          if (parametersBuilder_.isEmpty()) {
            parametersBuilder_.dispose();
            parametersBuilder_ = null;
            parameters_ = other.parameters_;
            bitField0_ = (bitField0_ & ~0x00000008);
            parametersBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getParametersFieldBuilder() : null;
          } else {
            parametersBuilder_.addAllMessages(other.parameters_);
          }
        }
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              alias_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000001;
              break;
            } // case 10
            case 18: {
              caption_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000002;
              break;
            } // case 18
            case 26: {
              description_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000004;
              break;
            } // case 26
            case 34: {
              ru.sovcombank.hackaton.proto.Parameter m =
                  input.readMessage(
                      ru.sovcombank.hackaton.proto.Parameter.parser(),
                      extensionRegistry);
              if (parametersBuilder_ == null) {
                ensureParametersIsMutable();
                parameters_.add(m);
              } else {
                parametersBuilder_.addMessage(m);
              }
              break;
            } // case 34
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private java.lang.Object alias_ = "";
    /**
     * <pre>
     * Идентификатор команды
     * </pre>
     *
     * <code>string alias = 1;</code>
     * @return The alias.
     */
    public java.lang.String getAlias() {
      java.lang.Object ref = alias_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        alias_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * Идентификатор команды
     * </pre>
     *
     * <code>string alias = 1;</code>
     * @return The bytes for alias.
     */
    public com.google.protobuf.ByteString
        getAliasBytes() {
      java.lang.Object ref = alias_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        alias_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * Идентификатор команды
     * </pre>
     *
     * <code>string alias = 1;</code>
     * @param value The alias to set.
     * @return This builder for chaining.
     */
    public Builder setAlias(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      alias_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Идентификатор команды
     * </pre>
     *
     * <code>string alias = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearAlias() {
      alias_ = getDefaultInstance().getAlias();
      bitField0_ = (bitField0_ & ~0x00000001);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Идентификатор команды
     * </pre>
     *
     * <code>string alias = 1;</code>
     * @param value The bytes for alias to set.
     * @return This builder for chaining.
     */
    public Builder setAliasBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      alias_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }

    private java.lang.Object caption_ = "";
    /**
     * <pre>
     * Заголовок команды
     * </pre>
     *
     * <code>optional string caption = 2;</code>
     * @return Whether the caption field is set.
     */
    public boolean hasCaption() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    /**
     * <pre>
     * Заголовок команды
     * </pre>
     *
     * <code>optional string caption = 2;</code>
     * @return The caption.
     */
    public java.lang.String getCaption() {
      java.lang.Object ref = caption_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        caption_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * Заголовок команды
     * </pre>
     *
     * <code>optional string caption = 2;</code>
     * @return The bytes for caption.
     */
    public com.google.protobuf.ByteString
        getCaptionBytes() {
      java.lang.Object ref = caption_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        caption_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * Заголовок команды
     * </pre>
     *
     * <code>optional string caption = 2;</code>
     * @param value The caption to set.
     * @return This builder for chaining.
     */
    public Builder setCaption(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      caption_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Заголовок команды
     * </pre>
     *
     * <code>optional string caption = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearCaption() {
      caption_ = getDefaultInstance().getCaption();
      bitField0_ = (bitField0_ & ~0x00000002);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Заголовок команды
     * </pre>
     *
     * <code>optional string caption = 2;</code>
     * @param value The bytes for caption to set.
     * @return This builder for chaining.
     */
    public Builder setCaptionBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      caption_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }

    private java.lang.Object description_ = "";
    /**
     * <pre>
     * Описание команды
     * </pre>
     *
     * <code>optional string description = 3;</code>
     * @return Whether the description field is set.
     */
    public boolean hasDescription() {
      return ((bitField0_ & 0x00000004) != 0);
    }
    /**
     * <pre>
     * Описание команды
     * </pre>
     *
     * <code>optional string description = 3;</code>
     * @return The description.
     */
    public java.lang.String getDescription() {
      java.lang.Object ref = description_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        description_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * Описание команды
     * </pre>
     *
     * <code>optional string description = 3;</code>
     * @return The bytes for description.
     */
    public com.google.protobuf.ByteString
        getDescriptionBytes() {
      java.lang.Object ref = description_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        description_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * Описание команды
     * </pre>
     *
     * <code>optional string description = 3;</code>
     * @param value The description to set.
     * @return This builder for chaining.
     */
    public Builder setDescription(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      description_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Описание команды
     * </pre>
     *
     * <code>optional string description = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearDescription() {
      description_ = getDefaultInstance().getDescription();
      bitField0_ = (bitField0_ & ~0x00000004);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Описание команды
     * </pre>
     *
     * <code>optional string description = 3;</code>
     * @param value The bytes for description to set.
     * @return This builder for chaining.
     */
    public Builder setDescriptionBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      description_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }

    private java.util.List<ru.sovcombank.hackaton.proto.Parameter> parameters_ =
      java.util.Collections.emptyList();
    private void ensureParametersIsMutable() {
      if (!((bitField0_ & 0x00000008) != 0)) {
        parameters_ = new java.util.ArrayList<ru.sovcombank.hackaton.proto.Parameter>(parameters_);
        bitField0_ |= 0x00000008;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        ru.sovcombank.hackaton.proto.Parameter, ru.sovcombank.hackaton.proto.Parameter.Builder, ru.sovcombank.hackaton.proto.ParameterOrBuilder> parametersBuilder_;

    /**
     * <pre>
     * Список параметров для команды
     * </pre>
     *
     * <code>repeated .ru.sovcombank.hackaton.proto.Parameter parameters = 4;</code>
     */
    public java.util.List<ru.sovcombank.hackaton.proto.Parameter> getParametersList() {
      if (parametersBuilder_ == null) {
        return java.util.Collections.unmodifiableList(parameters_);
      } else {
        return parametersBuilder_.getMessageList();
      }
    }
    /**
     * <pre>
     * Список параметров для команды
     * </pre>
     *
     * <code>repeated .ru.sovcombank.hackaton.proto.Parameter parameters = 4;</code>
     */
    public int getParametersCount() {
      if (parametersBuilder_ == null) {
        return parameters_.size();
      } else {
        return parametersBuilder_.getCount();
      }
    }
    /**
     * <pre>
     * Список параметров для команды
     * </pre>
     *
     * <code>repeated .ru.sovcombank.hackaton.proto.Parameter parameters = 4;</code>
     */
    public ru.sovcombank.hackaton.proto.Parameter getParameters(int index) {
      if (parametersBuilder_ == null) {
        return parameters_.get(index);
      } else {
        return parametersBuilder_.getMessage(index);
      }
    }
    /**
     * <pre>
     * Список параметров для команды
     * </pre>
     *
     * <code>repeated .ru.sovcombank.hackaton.proto.Parameter parameters = 4;</code>
     */
    public Builder setParameters(
        int index, ru.sovcombank.hackaton.proto.Parameter value) {
      if (parametersBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureParametersIsMutable();
        parameters_.set(index, value);
        onChanged();
      } else {
        parametersBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <pre>
     * Список параметров для команды
     * </pre>
     *
     * <code>repeated .ru.sovcombank.hackaton.proto.Parameter parameters = 4;</code>
     */
    public Builder setParameters(
        int index, ru.sovcombank.hackaton.proto.Parameter.Builder builderForValue) {
      if (parametersBuilder_ == null) {
        ensureParametersIsMutable();
        parameters_.set(index, builderForValue.build());
        onChanged();
      } else {
        parametersBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <pre>
     * Список параметров для команды
     * </pre>
     *
     * <code>repeated .ru.sovcombank.hackaton.proto.Parameter parameters = 4;</code>
     */
    public Builder addParameters(ru.sovcombank.hackaton.proto.Parameter value) {
      if (parametersBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureParametersIsMutable();
        parameters_.add(value);
        onChanged();
      } else {
        parametersBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <pre>
     * Список параметров для команды
     * </pre>
     *
     * <code>repeated .ru.sovcombank.hackaton.proto.Parameter parameters = 4;</code>
     */
    public Builder addParameters(
        int index, ru.sovcombank.hackaton.proto.Parameter value) {
      if (parametersBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureParametersIsMutable();
        parameters_.add(index, value);
        onChanged();
      } else {
        parametersBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <pre>
     * Список параметров для команды
     * </pre>
     *
     * <code>repeated .ru.sovcombank.hackaton.proto.Parameter parameters = 4;</code>
     */
    public Builder addParameters(
        ru.sovcombank.hackaton.proto.Parameter.Builder builderForValue) {
      if (parametersBuilder_ == null) {
        ensureParametersIsMutable();
        parameters_.add(builderForValue.build());
        onChanged();
      } else {
        parametersBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <pre>
     * Список параметров для команды
     * </pre>
     *
     * <code>repeated .ru.sovcombank.hackaton.proto.Parameter parameters = 4;</code>
     */
    public Builder addParameters(
        int index, ru.sovcombank.hackaton.proto.Parameter.Builder builderForValue) {
      if (parametersBuilder_ == null) {
        ensureParametersIsMutable();
        parameters_.add(index, builderForValue.build());
        onChanged();
      } else {
        parametersBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <pre>
     * Список параметров для команды
     * </pre>
     *
     * <code>repeated .ru.sovcombank.hackaton.proto.Parameter parameters = 4;</code>
     */
    public Builder addAllParameters(
        java.lang.Iterable<? extends ru.sovcombank.hackaton.proto.Parameter> values) {
      if (parametersBuilder_ == null) {
        ensureParametersIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, parameters_);
        onChanged();
      } else {
        parametersBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <pre>
     * Список параметров для команды
     * </pre>
     *
     * <code>repeated .ru.sovcombank.hackaton.proto.Parameter parameters = 4;</code>
     */
    public Builder clearParameters() {
      if (parametersBuilder_ == null) {
        parameters_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000008);
        onChanged();
      } else {
        parametersBuilder_.clear();
      }
      return this;
    }
    /**
     * <pre>
     * Список параметров для команды
     * </pre>
     *
     * <code>repeated .ru.sovcombank.hackaton.proto.Parameter parameters = 4;</code>
     */
    public Builder removeParameters(int index) {
      if (parametersBuilder_ == null) {
        ensureParametersIsMutable();
        parameters_.remove(index);
        onChanged();
      } else {
        parametersBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <pre>
     * Список параметров для команды
     * </pre>
     *
     * <code>repeated .ru.sovcombank.hackaton.proto.Parameter parameters = 4;</code>
     */
    public ru.sovcombank.hackaton.proto.Parameter.Builder getParametersBuilder(
        int index) {
      return getParametersFieldBuilder().getBuilder(index);
    }
    /**
     * <pre>
     * Список параметров для команды
     * </pre>
     *
     * <code>repeated .ru.sovcombank.hackaton.proto.Parameter parameters = 4;</code>
     */
    public ru.sovcombank.hackaton.proto.ParameterOrBuilder getParametersOrBuilder(
        int index) {
      if (parametersBuilder_ == null) {
        return parameters_.get(index);  } else {
        return parametersBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <pre>
     * Список параметров для команды
     * </pre>
     *
     * <code>repeated .ru.sovcombank.hackaton.proto.Parameter parameters = 4;</code>
     */
    public java.util.List<? extends ru.sovcombank.hackaton.proto.ParameterOrBuilder> 
         getParametersOrBuilderList() {
      if (parametersBuilder_ != null) {
        return parametersBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(parameters_);
      }
    }
    /**
     * <pre>
     * Список параметров для команды
     * </pre>
     *
     * <code>repeated .ru.sovcombank.hackaton.proto.Parameter parameters = 4;</code>
     */
    public ru.sovcombank.hackaton.proto.Parameter.Builder addParametersBuilder() {
      return getParametersFieldBuilder().addBuilder(
          ru.sovcombank.hackaton.proto.Parameter.getDefaultInstance());
    }
    /**
     * <pre>
     * Список параметров для команды
     * </pre>
     *
     * <code>repeated .ru.sovcombank.hackaton.proto.Parameter parameters = 4;</code>
     */
    public ru.sovcombank.hackaton.proto.Parameter.Builder addParametersBuilder(
        int index) {
      return getParametersFieldBuilder().addBuilder(
          index, ru.sovcombank.hackaton.proto.Parameter.getDefaultInstance());
    }
    /**
     * <pre>
     * Список параметров для команды
     * </pre>
     *
     * <code>repeated .ru.sovcombank.hackaton.proto.Parameter parameters = 4;</code>
     */
    public java.util.List<ru.sovcombank.hackaton.proto.Parameter.Builder> 
         getParametersBuilderList() {
      return getParametersFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        ru.sovcombank.hackaton.proto.Parameter, ru.sovcombank.hackaton.proto.Parameter.Builder, ru.sovcombank.hackaton.proto.ParameterOrBuilder> 
        getParametersFieldBuilder() {
      if (parametersBuilder_ == null) {
        parametersBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            ru.sovcombank.hackaton.proto.Parameter, ru.sovcombank.hackaton.proto.Parameter.Builder, ru.sovcombank.hackaton.proto.ParameterOrBuilder>(
                parameters_,
                ((bitField0_ & 0x00000008) != 0),
                getParentForChildren(),
                isClean());
        parameters_ = null;
      }
      return parametersBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:ru.sovcombank.hackaton.proto.OwnCommand)
  }

  // @@protoc_insertion_point(class_scope:ru.sovcombank.hackaton.proto.OwnCommand)
  private static final ru.sovcombank.hackaton.proto.OwnCommand DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new ru.sovcombank.hackaton.proto.OwnCommand();
  }

  public static ru.sovcombank.hackaton.proto.OwnCommand getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<OwnCommand>
      PARSER = new com.google.protobuf.AbstractParser<OwnCommand>() {
    @java.lang.Override
    public OwnCommand parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<OwnCommand> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<OwnCommand> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public ru.sovcombank.hackaton.proto.OwnCommand getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

