// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Parameter.proto

package ru.sovcombank.hackaton.proto;

public interface ParameterOrBuilder extends
    // @@protoc_insertion_point(interface_extends:ru.sovcombank.hackaton.proto.Parameter)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * Идентификатор параметра
   * </pre>
   *
   * <code>string alias = 1;</code>
   * @return The alias.
   */
  java.lang.String getAlias();
  /**
   * <pre>
   * Идентификатор параметра
   * </pre>
   *
   * <code>string alias = 1;</code>
   * @return The bytes for alias.
   */
  com.google.protobuf.ByteString
      getAliasBytes();

  /**
   * <pre>
   * Заголовок параметра
   * </pre>
   *
   * <code>optional string caption = 2;</code>
   * @return Whether the caption field is set.
   */
  boolean hasCaption();
  /**
   * <pre>
   * Заголовок параметра
   * </pre>
   *
   * <code>optional string caption = 2;</code>
   * @return The caption.
   */
  java.lang.String getCaption();
  /**
   * <pre>
   * Заголовок параметра
   * </pre>
   *
   * <code>optional string caption = 2;</code>
   * @return The bytes for caption.
   */
  com.google.protobuf.ByteString
      getCaptionBytes();

  /**
   * <pre>
   * Подсказка
   * </pre>
   *
   * <code>optional string hint = 3;</code>
   * @return Whether the hint field is set.
   */
  boolean hasHint();
  /**
   * <pre>
   * Подсказка
   * </pre>
   *
   * <code>optional string hint = 3;</code>
   * @return The hint.
   */
  java.lang.String getHint();
  /**
   * <pre>
   * Подсказка
   * </pre>
   *
   * <code>optional string hint = 3;</code>
   * @return The bytes for hint.
   */
  com.google.protobuf.ByteString
      getHintBytes();

  /**
   * <pre>
   * Значение
   * </pre>
   *
   * <code>optional .ru.sovcombank.hackaton.proto.ValueRef value = 4;</code>
   * @return Whether the value field is set.
   */
  boolean hasValue();
  /**
   * <pre>
   * Значение
   * </pre>
   *
   * <code>optional .ru.sovcombank.hackaton.proto.ValueRef value = 4;</code>
   * @return The value.
   */
  ru.sovcombank.hackaton.proto.ValueRef getValue();
  /**
   * <pre>
   * Значение
   * </pre>
   *
   * <code>optional .ru.sovcombank.hackaton.proto.ValueRef value = 4;</code>
   */
  ru.sovcombank.hackaton.proto.ValueRefOrBuilder getValueOrBuilder();
}
