// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Request.proto

package ru.sovcombank.hackaton.proto;

public final class RequestProto {
  private RequestProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ru_sovcombank_hackaton_proto_Request_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ru_sovcombank_hackaton_proto_Request_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\rRequest.proto\022\034ru.sovcombank.hackaton." +
      "proto\032\022MessageEnums.proto\032\020OwnCommand.pr" +
      "oto\"\344\001\n\007Request\022:\n\007command\030\001 \001(\0162).ru.so" +
      "vcombank.hackaton.proto.CommandType\022E\n\016c" +
      "ommandForExec\030\002 \001(\0132(.ru.sovcombank.hack" +
      "aton.proto.OwnCommandH\000\210\001\001\022C\n\021supportedC" +
      "ommands\030\003 \003(\0132(.ru.sovcombank.hackaton.p" +
      "roto.OwnCommandB\021\n\017_commandForExecB\022B\014Re" +
      "questProtoH\001P\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          ru.sovcombank.hackaton.proto.MessageEnumsProto.getDescriptor(),
          ru.sovcombank.hackaton.proto.OwnCommandProto.getDescriptor(),
        });
    internal_static_ru_sovcombank_hackaton_proto_Request_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_ru_sovcombank_hackaton_proto_Request_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ru_sovcombank_hackaton_proto_Request_descriptor,
        new java.lang.String[] { "Command", "CommandForExec", "SupportedCommands", "CommandForExec", });
    ru.sovcombank.hackaton.proto.MessageEnumsProto.getDescriptor();
    ru.sovcombank.hackaton.proto.OwnCommandProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
