// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Response.proto

package ru.sovcombank.hackaton.proto;

public interface ResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:ru.sovcombank.hackaton.proto.Response)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * Тип команды на которую отвечаем. (ctHandshake - ответ на приветствие, ctExecCommand - ответ на исполнение команды, ctStatus - ответ на запрос статуса сервиса.)
   * </pre>
   *
   * <code>.ru.sovcombank.hackaton.proto.CommandType command = 1;</code>
   * @return The enum numeric value on the wire for command.
   */
  int getCommandValue();
  /**
   * <pre>
   * Тип команды на которую отвечаем. (ctHandshake - ответ на приветствие, ctExecCommand - ответ на исполнение команды, ctStatus - ответ на запрос статуса сервиса.)
   * </pre>
   *
   * <code>.ru.sovcombank.hackaton.proto.CommandType command = 1;</code>
   * @return The command.
   */
  ru.sovcombank.hackaton.proto.MessageEnumsProto.CommandType getCommand();

  /**
   * <pre>
   * Тип ответа
   * </pre>
   *
   * <code>.ru.sovcombank.hackaton.proto.AnswerType answerType = 2;</code>
   * @return The enum numeric value on the wire for answerType.
   */
  int getAnswerTypeValue();
  /**
   * <pre>
   * Тип ответа
   * </pre>
   *
   * <code>.ru.sovcombank.hackaton.proto.AnswerType answerType = 2;</code>
   * @return The answerType.
   */
  ru.sovcombank.hackaton.proto.MessageEnumsProto.AnswerType getAnswerType();

  /**
   * <pre>
   * Описание ошибки в случае если тип ответа atNotSupported или atAnswerError
   * </pre>
   *
   * <code>optional string errorText = 3;</code>
   * @return Whether the errorText field is set.
   */
  boolean hasErrorText();
  /**
   * <pre>
   * Описание ошибки в случае если тип ответа atNotSupported или atAnswerError
   * </pre>
   *
   * <code>optional string errorText = 3;</code>
   * @return The errorText.
   */
  java.lang.String getErrorText();
  /**
   * <pre>
   * Описание ошибки в случае если тип ответа atNotSupported или atAnswerError
   * </pre>
   *
   * <code>optional string errorText = 3;</code>
   * @return The bytes for errorText.
   */
  com.google.protobuf.ByteString
      getErrorTextBytes();

  /**
   * <pre>
   * Статус
   * </pre>
   *
   * <code>optional .ru.sovcombank.hackaton.proto.Status status = 4;</code>
   * @return Whether the status field is set.
   */
  boolean hasStatus();
  /**
   * <pre>
   * Статус
   * </pre>
   *
   * <code>optional .ru.sovcombank.hackaton.proto.Status status = 4;</code>
   * @return The status.
   */
  ru.sovcombank.hackaton.proto.Status getStatus();
  /**
   * <pre>
   * Статус
   * </pre>
   *
   * <code>optional .ru.sovcombank.hackaton.proto.Status status = 4;</code>
   */
  ru.sovcombank.hackaton.proto.StatusOrBuilder getStatusOrBuilder();
}
