// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Response.proto

package ru.sovcombank.hackaton.proto;

public final class ResponseProto {
  private ResponseProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ru_sovcombank_hackaton_proto_Response_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ru_sovcombank_hackaton_proto_Response_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\016Response.proto\022\034ru.sovcombank.hackaton" +
      ".proto\032\022MessageEnums.proto\032\014Status.proto" +
      "\"\360\001\n\010Response\022:\n\007command\030\001 \001(\0162).ru.sovc" +
      "ombank.hackaton.proto.CommandType\022<\n\nans" +
      "werType\030\002 \001(\0162(.ru.sovcombank.hackaton.p" +
      "roto.AnswerType\022\026\n\terrorText\030\003 \001(\tH\000\210\001\001\022" +
      "9\n\006status\030\004 \001(\0132$.ru.sovcombank.hackaton" +
      ".proto.StatusH\001\210\001\001B\014\n\n_errorTextB\t\n\007_sta" +
      "tusB\023B\rResponseProtoH\001P\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          ru.sovcombank.hackaton.proto.MessageEnumsProto.getDescriptor(),
          ru.sovcombank.hackaton.proto.StatusProto.getDescriptor(),
        });
    internal_static_ru_sovcombank_hackaton_proto_Response_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_ru_sovcombank_hackaton_proto_Response_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ru_sovcombank_hackaton_proto_Response_descriptor,
        new java.lang.String[] { "Command", "AnswerType", "ErrorText", "Status", "ErrorText", "Status", });
    ru.sovcombank.hackaton.proto.MessageEnumsProto.getDescriptor();
    ru.sovcombank.hackaton.proto.StatusProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
