// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ValueRef.proto

package ru.sovcombank.hackaton.proto;

public final class ValueRefProto {
  private ValueRefProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ru_sovcombank_hackaton_proto_ValueRef_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ru_sovcombank_hackaton_proto_ValueRef_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\016ValueRef.proto\022\034ru.sovcombank.hackaton" +
      ".proto\032\022MessageEnums.proto\"\202\001\n\010ValueRef\022" +
      "8\n\010dataType\030\001 \001(\0162&.ru.sovcombank.hackat" +
      "on.proto.DataType\022\023\n\006format\030\002 \001(\tH\000\210\001\001\022\022" +
      "\n\005value\030\003 \001(\tH\001\210\001\001B\t\n\007_formatB\010\n\006_valueB" +
      "\023B\rValueRefProtoH\001P\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          ru.sovcombank.hackaton.proto.MessageEnumsProto.getDescriptor(),
        });
    internal_static_ru_sovcombank_hackaton_proto_ValueRef_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_ru_sovcombank_hackaton_proto_ValueRef_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ru_sovcombank_hackaton_proto_ValueRef_descriptor,
        new java.lang.String[] { "DataType", "Format", "Value", "Format", "Value", });
    ru.sovcombank.hackaton.proto.MessageEnumsProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
